packages:
  - "apps/sdk"
  - "apps/web"
  - "apps/server"
  - "packages/components/*"
  - "packages/radix/*"
  - "packages/shared/*"
  - "packages/tailwind"
  - "packages/widget"
  - "packages/license"
  - "packages/helpers"
  - "packages/types"
