packages:
  - "apps/sdk"
  - "apps/web"
  - "apps/server"
  - "packages/radix/*"
  - "packages/ui"
  - "packages/frame"
  - "packages/constants"
  - "packages/dom"
  - "packages/icons"
  - "packages/tailwind"
  - "packages/widget"
  - "packages/license"
  - "packages/helpers"
  - "packages/types"
  - "packages/business-components"
  - "packages/builder"
  - "packages/builder-v2"
  - "packages/contexts"
  - "packages/editor"
  - "packages/finder"
  - "packages/gql"
  - "packages/i18n"
  - "packages/hooks"
