// Common RemixIcon presets for quick setup
// Import only the icons you need to keep bundle size small
// This file registers commonly used icons for dynamic lookup in SDK
import {
  RiHomeLine,
  RiHomeFill,
  RiSettingsLine,
  RiSettingsFill,
  RiUserLine,
  RiUserFill,
  RiNotificationLine,
  RiNotificationFill,
  RiSearchLine,
  RiSearchFill,
  RiHeartLine,
  RiHeartFill,
  RiStarLine,
  RiStarFill,
  RiArrowRightLine,
  RiArrowLeftLine,
  RiArrowUpLine,
  RiArrowDownLine,
  RiCheckLine,
  RiCloseLine,
  RiAddLine,
  RiSubtractLine,
  RiEditLine,
  RiDeleteBinLine,
  RiDownloadLine,
  RiUploadLine,
  RiShareLine,
  RiMoreLine,
  RiMenuLine,
  RiCloseCircleLine,
  RiCheckboxCircleLine,
  RiErrorWarningLine,
  RiInformationLine,
  RiQuestionLine,
  RiLockLine,
  RiLockUnlockLine,
  RiEyeLine,
  RiEyeOffLine,
  RiMailLine,
  RiPhoneLine,
  RiGlobalLine,
  RiCalendarLine,
  RiTimeLine,
  RiFileLine,
  RiFolderLine,
  RiImageLine,
  RiVideoLine,
  RiMusicLine,
  RiBookmarkLine,
  RiBookmarkFill,
  RiFlagLine,
  RiFlagFill,
  RiThumbUpLine,
  RiThumbDownLine,
  RiChat1Line,
  RiChat1Fill,
  RiSendPlaneLine,
  RiReplyLine,
  RiRefreshLine,
  RiRestartLine,
  RiShutDownLine,
  RiWifiLine,
  RiWifiOffLine,
  RiBluetoothLine,
  RiBatteryLine,
  RiBatteryChargeLine,
  RiFlashlightLine,
  RiVolumeUpLine,
  RiVolumeDownLine,
  RiVolumeMuteLine,
  RiFullscreenLine,
  RiFullscreenExitLine,
  RiZoomInLine,
  RiZoomOutLine,
  RiFocusLine,
  RiCropLine,
  RiFilterLine,
  RiEqualizerLine,
  RiPaletteLine,
  RiBrushLine,
  RiPaintBrushLine,
  RiScissorsLine,
  RiEraserLine,
  RiSquareLine,
  RiSquareFill,
  RiCircleLine,
  RiCircleFill,
  RiTriangleLine,
  RiTriangleFill,
  RiArrowUpCircleLine,
  RiArrowDownCircleLine,
  RiArrowLeftCircleLine,
  RiArrowRightCircleLine,
  RiSkipBackLine,
  RiSkipForwardLine,
  RiPlayLine,
  RiPauseLine,
  RiStopLine,
  RiRecordCircleLine,
  RiRepeatLine,
  RiShuffleLine,
  RiPlayListLine,
  RiPlayListAddLine,
  RiFacebookLine,
  RiFacebookFill,
  RiTwitterLine,
  RiTwitterFill,
  RiInstagramLine,
  RiInstagramFill,
  RiLinkedinLine,
  RiLinkedinFill,
  RiGithubLine,
  RiGithubFill,
  RiGoogleLine,
  RiGoogleFill,
  RiAppleLine,
  RiAppleFill,
  RiMicrosoftLine,
  RiMicrosoftFill,
  RiShoppingCartLine,
  RiShoppingCartFill,
  RiShoppingBagLine,
  RiShoppingBagFill,
  RiStoreLine,
  RiStoreFill,
  RiPriceTagLine,
  RiPriceTagFill,
  RiGiftLine,
  RiGiftFill,
  RiTrophyLine,
  RiTrophyFill,
  RiAwardLine,
  RiAwardFill,
  RiMedalLine,
  RiMedalFill,
  RiVipCrown2Line,
  RiVipCrown2Fill,
  RiMapPinLine,
  RiMapPinFill,
  RiMapLine,
  RiMapFill,
  RiNavigationLine,
  RiNavigationFill,
  RiCompassLine,
  RiCompassFill,
} from '@remixicon/react';
import { registerIcons } from './remix-icon';

// Register common icons for easy access
// Users can register more icons as needed using registerIcon() or registerIcons()
registerIcons({
  // Basic UI
  'home-line': RiHomeLine,
  'home-fill': RiHomeFill,
  'settings-line': RiSettingsLine,
  'settings-fill': RiSettingsFill,
  'user-line': RiUserLine,
  'user-fill': RiUserFill,
  'notification-line': RiNotificationLine,
  'notification-fill': RiNotificationFill,
  'search-line': RiSearchLine,
  'search-fill': RiSearchFill,
  'heart-line': RiHeartLine,
  'heart-fill': RiHeartFill,
  'star-line': RiStarLine,
  'star-fill': RiStarFill,
  // Navigation
  'arrow-right-line': RiArrowRightLine,
  'arrow-left-line': RiArrowLeftLine,
  'arrow-up-line': RiArrowUpLine,
  'arrow-down-line': RiArrowDownLine,
  // Actions
  'check-line': RiCheckLine,
  'close-line': RiCloseLine,
  'add-line': RiAddLine,
  'subtract-line': RiSubtractLine,
  'edit-line': RiEditLine,
  'delete-line': RiDeleteBinLine,
  'delete-bin-line': RiDeleteBinLine,
  'download-line': RiDownloadLine,
  'upload-line': RiUploadLine,
  'share-line': RiShareLine,
  'more-line': RiMoreLine,
  'menu-line': RiMenuLine,
  // Status
  'close-circle-line': RiCloseCircleLine,
  'check-circle-line': RiCheckboxCircleLine,
  'checkbox-circle-line': RiCheckboxCircleLine,
  'error-warning-line': RiErrorWarningLine,
  'information-line': RiInformationLine,
  'question-line': RiQuestionLine,
  // Security
  'lock-line': RiLockLine,
  'lock-unlock-line': RiLockUnlockLine,
  'eye-line': RiEyeLine,
  'eye-off-line': RiEyeOffLine,
  // Communication
  'mail-line': RiMailLine,
  'phone-line': RiPhoneLine,
  'chat-line': RiChat1Line,
  'chat-fill': RiChat1Fill,
  'chat1-line': RiChat1Line,
  'chat1-fill': RiChat1Fill,
  'send-line': RiSendPlaneLine,
  'send-plane-line': RiSendPlaneLine,
  'reply-line': RiReplyLine,
  // Media
  'image-line': RiImageLine,
  'video-line': RiVideoLine,
  'music-line': RiMusicLine,
  'file-line': RiFileLine,
  'folder-line': RiFolderLine,
  // Social
  'bookmark-line': RiBookmarkLine,
  'bookmark-fill': RiBookmarkFill,
  'flag-line': RiFlagLine,
  'flag-fill': RiFlagFill,
  'thumb-up-line': RiThumbUpLine,
  'thumb-down-line': RiThumbDownLine,
  // System
  'refresh-line': RiRefreshLine,
  'restart-line': RiRestartLine,
  'shut-down-line': RiShutDownLine,
  'wifi-line': RiWifiLine,
  'wifi-off-line': RiWifiOffLine,
  'bluetooth-line': RiBluetoothLine,
  'battery-line': RiBatteryLine,
  'battery-charge-line': RiBatteryChargeLine,
  'flashlight-line': RiFlashlightLine,
  'volume-up-line': RiVolumeUpLine,
  'volume-down-line': RiVolumeDownLine,
  'volume-mute-line': RiVolumeMuteLine,
  'fullscreen-line': RiFullscreenLine,
  'fullscreen-exit-line': RiFullscreenExitLine,
  'zoom-in-line': RiZoomInLine,
  'zoom-out-line': RiZoomOutLine,
  'focus-line': RiFocusLine,
  'crop-line': RiCropLine,
  'filter-line': RiFilterLine,
  'equalizer-line': RiEqualizerLine,
  'palette-line': RiPaletteLine,
  'brush-line': RiBrushLine,
  'paint-brush-line': RiPaintBrushLine,
  'scissors-line': RiScissorsLine,
  'eraser-line': RiEraserLine,
  // Shapes
  'square-line': RiSquareLine,
  'square-fill': RiSquareFill,
  'circle-line': RiCircleLine,
  'circle-fill': RiCircleFill,
  'triangle-line': RiTriangleLine,
  'triangle-fill': RiTriangleFill,
  // Arrows
  'arrow-up-circle-line': RiArrowUpCircleLine,
  'arrow-down-circle-line': RiArrowDownCircleLine,
  'arrow-left-circle-line': RiArrowLeftCircleLine,
  'arrow-right-circle-line': RiArrowRightCircleLine,
  // Media Controls
  'skip-back-line': RiSkipBackLine,
  'skip-forward-line': RiSkipForwardLine,
  'play-line': RiPlayLine,
  'pause-line': RiPauseLine,
  'stop-line': RiStopLine,
  'record-circle-line': RiRecordCircleLine,
  'repeat-line': RiRepeatLine,
  'shuffle-line': RiShuffleLine,
  'play-list-line': RiPlayListLine,
  'play-list-add-line': RiPlayListAddLine,
  // Social Media
  'facebook-line': RiFacebookLine,
  'facebook-fill': RiFacebookFill,
  'twitter-line': RiTwitterLine,
  'twitter-fill': RiTwitterFill,
  'instagram-line': RiInstagramLine,
  'instagram-fill': RiInstagramFill,
  'linkedin-line': RiLinkedinLine,
  'linkedin-fill': RiLinkedinFill,
  'github-line': RiGithubLine,
  'github-fill': RiGithubFill,
  'google-line': RiGoogleLine,
  'google-fill': RiGoogleFill,
  'apple-line': RiAppleLine,
  'apple-fill': RiAppleFill,
  'microsoft-line': RiMicrosoftLine,
  'microsoft-fill': RiMicrosoftFill,
  // Shopping
  'shopping-cart-line': RiShoppingCartLine,
  'shopping-cart-fill': RiShoppingCartFill,
  'shopping-bag-line': RiShoppingBagLine,
  'shopping-bag-fill': RiShoppingBagFill,
  'store-line': RiStoreLine,
  'store-fill': RiStoreFill,
  'price-tag-line': RiPriceTagLine,
  'price-tag-fill': RiPriceTagFill,
  'gift-line': RiGiftLine,
  'gift-fill': RiGiftFill,
  // Awards
  'trophy-line': RiTrophyLine,
  'trophy-fill': RiTrophyFill,
  'award-line': RiAwardLine,
  'award-fill': RiAwardFill,
  'medal-line': RiMedalLine,
  'medal-fill': RiMedalFill,
  'crown-line': RiVipCrown2Line,
  'crown-fill': RiVipCrown2Fill,
  'vip-crown2-line': RiVipCrown2Line,
  'vip-crown2-fill': RiVipCrown2Fill,
  // Navigation & Location
  'map-pin-line': RiMapPinLine,
  'map-pin-fill': RiMapPinFill,
  'map-line': RiMapLine,
  'map-fill': RiMapFill,
  'navigation-line': RiNavigationLine,
  'navigation-fill': RiNavigationFill,
  'compass-line': RiCompassLine,
  'compass-fill': RiCompassFill,
  // Time & Date
  'calendar-line': RiCalendarLine,
  'time-line': RiTimeLine,
  'global-line': RiGlobalLine,
});
