import type { LocaleOption } from '@usertour/types';

/**
 * Curated locale catalog for the localization picker: the language-region
 * combinations content teams actually translate into, plus region-less
 * entries (e.g. `ar`) for languages usually translated once per language --
 * delivery matches those by primary subtag. The picker is a convenience,
 * not a gate: the create/edit dialogs accept any hand-typed BCP-47 code.
 */
export const locates: LocaleOption[] = [
  { locale: 'sq-AL', name: 'Albanian (Albania)' },
  { locale: 'ar', name: 'Arabic' },
  { locale: 'bs-BA', name: 'Bosnian (Bosnia)' },
  { locale: 'bg-BG', name: 'Bulgarian (Bulgaria)' },
  { locale: 'zh-CN', name: "Chinese (Simplified, People's Republic of China)" },
  { locale: 'zh-TW', name: 'Chinese, Mandarin (Traditional, Taiwan)' },
  { locale: 'hr-HR', name: 'Croatian (Croatia)' },
  { locale: 'cs-CZ', name: 'Czech (Czech Republic)' },
  { locale: 'da-DK', name: 'Danish (Denmark)' },
  { locale: 'nl-BE', name: 'Dutch (Belgium)' },
  { locale: 'nl-NL', name: 'Dutch (Netherlands)' },
  { locale: 'en-GB', name: 'English (UK)' },
  { locale: 'en-US', name: 'English (US)' },
  { locale: 'et-EE', name: 'Estonian (Estonia)' },
  { locale: 'fi-FI', name: 'Finnish (Finland)' },
  { locale: 'fr-FR', name: 'French (France)' },
  { locale: 'fr-BE', name: 'French (Belgium)' },
  { locale: 'de-DE', name: 'German (Germany)' },
  { locale: 'el-GR', name: 'Greek (Greece)' },
  { locale: 'he-IL', name: 'Hebrew (Israel)' },
  { locale: 'hi-IN', name: 'Hindi (India)' },
  { locale: 'hu-HU', name: 'Hungarian (Hungary)' },
  { locale: 'is-IS', name: 'Icelandic (Iceland)' },
  { locale: 'id-ID', name: 'Indonesian (Indonesia)' },
  { locale: 'it-IT', name: 'Italian (Italy)' },
  { locale: 'ja-JP', name: 'Japanese (Japan)' },
  { locale: 'ko-KR', name: 'Korean (Korea)' },
  { locale: 'lv-LV', name: 'Latvian (Latvia)' },
  { locale: 'lt-LT', name: 'Lithuanian (Lithuania)' },
  { locale: 'nb-NO', name: 'Norwegian Bokmål (Norway)' },
  { locale: 'pl-PL', name: 'Polish (Poland)' },
  { locale: 'pt-BR', name: 'Portuguese (Brazil)' },
  { locale: 'pt-PT', name: 'Portuguese (Portugal)' },
  { locale: 'ro-RO', name: 'Romanian (Romania)' },
  { locale: 'ru-RU', name: 'Russian (Russia)' },
  { locale: 'sk-SK', name: 'Slovak (Slovakia)' },
  { locale: 'sl-SI', name: 'Slovenian (Slovenia)' },
  { locale: 'es-AR', name: 'Spanish (Argentina)' },
  { locale: 'es-CL', name: 'Spanish (Chile)' },
  { locale: 'es-CO', name: 'Spanish (Colombia)' },
  { locale: 'es-MX', name: 'Spanish (Mexico)' },
  { locale: 'es-ES', name: 'Spanish (Spain)' },
  { locale: 'sv-SE', name: 'Swedish (Sweden)' },
  { locale: 'tg-TJ', name: 'Tajik (Tajikistan)' },
  { locale: 'th-TH', name: 'Thai (Thailand)' },
  { locale: 'tr-TR', name: 'Turkish (Turkey)' },
  { locale: 'uk-UA', name: 'Ukrainian (Ukraine)' },
  { locale: 'vi-VN', name: 'Vietnamese (Vietnam)' },
];
