import {
  AttributeBizTypes,
  AttributeDataType,
  BizEvents,
  CompanyAttributes,
  EventAttributes,
  UserAttributes,
} from '@usertour/types';

/**
 * Default events / attributes seeded into every project. Single source shared by
 * the app's project-creation path (apps/server initialization) and the
 * deploy-time backfill (apps/server/prisma/project-defaults), so a project
 * created before a default was added gets it backfilled with identical rows.
 */
export interface ProjectDefaultAttribute {
  codeName: string;
  displayName: string;
  bizType: AttributeBizTypes;
  dataType: AttributeDataType;
  description?: string;
}

export const defaultEvents = [
  {
    displayName: 'Page Viewed',
    codeName: BizEvents.PAGE_VIEWED,
    description: 'When a page is viewed in your app',
    attributes: [
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Flow Started',
    codeName: BizEvents.FLOW_STARTED,
    description: 'When a flow session starts',
    attributes: [
      EventAttributes.FLOW_ID,
      EventAttributes.FLOW_NAME,
      EventAttributes.FLOW_SESSION_ID,
      EventAttributes.FLOW_START_REASON,
      EventAttributes.FLOW_VERSION_ID,
      EventAttributes.FLOW_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Flow Dismissed/Ended',
    codeName: BizEvents.FLOW_ENDED,
    description: 'When a flow is dismissed',
    attributes: [
      EventAttributes.FLOW_END_REASON,
      EventAttributes.FLOW_ID,
      EventAttributes.FLOW_NAME,
      EventAttributes.FLOW_SESSION_ID,
      EventAttributes.FLOW_STEP_CVID,
      EventAttributes.FLOW_STEP_ID,
      EventAttributes.FLOW_STEP_NAME,
      EventAttributes.FLOW_STEP_NUMBER,
      EventAttributes.FLOW_STEP_PROGRESS,
      EventAttributes.FLOW_VERSION_ID,
      EventAttributes.FLOW_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Flow Step Seen',
    codeName: BizEvents.FLOW_STEP_SEEN,
    description: 'When a flow step becomes visible',
    attributes: [
      EventAttributes.FLOW_ID,
      EventAttributes.FLOW_NAME,
      EventAttributes.FLOW_SESSION_ID,
      EventAttributes.FLOW_STEP_CVID,
      EventAttributes.FLOW_STEP_ID,
      EventAttributes.FLOW_STEP_NAME,
      EventAttributes.FLOW_STEP_NUMBER,
      EventAttributes.FLOW_STEP_PROGRESS,
      EventAttributes.FLOW_VERSION_ID,
      EventAttributes.FLOW_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Flow Step Completed',
    codeName: BizEvents.FLOW_STEP_COMPLETED,
    description: "When a flow step's completion conditions are met",
    attributes: [
      EventAttributes.FLOW_ID,
      EventAttributes.FLOW_NAME,
      EventAttributes.FLOW_SESSION_ID,
      EventAttributes.FLOW_STEP_CVID,
      EventAttributes.FLOW_STEP_ID,
      EventAttributes.FLOW_STEP_NAME,
      EventAttributes.FLOW_STEP_NUMBER,
      EventAttributes.FLOW_STEP_PROGRESS,
      EventAttributes.FLOW_VERSION_ID,
      EventAttributes.FLOW_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Flow Completed',
    codeName: BizEvents.FLOW_COMPLETED,
    description: 'When a flow reaches a goal step',
    attributes: [
      EventAttributes.FLOW_ID,
      EventAttributes.FLOW_NAME,
      EventAttributes.FLOW_SESSION_ID,
      EventAttributes.FLOW_STEP_CVID,
      EventAttributes.FLOW_STEP_ID,
      EventAttributes.FLOW_STEP_NAME,
      EventAttributes.FLOW_STEP_NUMBER,
      EventAttributes.FLOW_STEP_PROGRESS,
      EventAttributes.FLOW_VERSION_ID,
      EventAttributes.FLOW_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Tooltip Target Missing',
    codeName: BizEvents.TOOLTIP_TARGET_MISSING,
    description: 'When a tooltip step cannot find its anchor element on the page',
    attributes: [
      EventAttributes.FLOW_ID,
      EventAttributes.FLOW_NAME,
      EventAttributes.FLOW_SESSION_ID,
      EventAttributes.FLOW_STEP_CVID,
      EventAttributes.FLOW_STEP_ID,
      EventAttributes.FLOW_STEP_NAME,
      EventAttributes.FLOW_STEP_NUMBER,
      EventAttributes.FLOW_STEP_PROGRESS,
      EventAttributes.FLOW_VERSION_ID,
      EventAttributes.FLOW_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Launcher Activated',
    codeName: BizEvents.LAUNCHER_ACTIVATED,
    description: 'When a launcher is activated by click or hover',
    attributes: [
      EventAttributes.LAUNCHER_ID,
      EventAttributes.LAUNCHER_NAME,
      EventAttributes.LAUNCHER_SESSION_ID,
      EventAttributes.LAUNCHER_VERSION_ID,
      EventAttributes.LAUNCHER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Launcher Dismissed',
    codeName: BizEvents.LAUNCHER_DISMISSED,
    description: 'When a launcher is dismissed',
    attributes: [
      EventAttributes.LAUNCHER_ID,
      EventAttributes.LAUNCHER_NAME,
      EventAttributes.LAUNCHER_SESSION_ID,
      EventAttributes.LAUNCHER_VERSION_ID,
      EventAttributes.LAUNCHER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Launcher Seen',
    codeName: BizEvents.LAUNCHER_SEEN,
    description: 'When a launcher becomes visible',
    attributes: [
      EventAttributes.LAUNCHER_ID,
      EventAttributes.LAUNCHER_NAME,
      EventAttributes.LAUNCHER_SESSION_ID,
      EventAttributes.LAUNCHER_VERSION_ID,
      EventAttributes.LAUNCHER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Banner Seen',
    codeName: BizEvents.BANNER_SEEN,
    description: 'When a banner becomes visible',
    attributes: [
      EventAttributes.BANNER_ID,
      EventAttributes.BANNER_NAME,
      EventAttributes.BANNER_SESSION_ID,
      EventAttributes.BANNER_VERSION_ID,
      EventAttributes.BANNER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Banner Dismissed',
    codeName: BizEvents.BANNER_DISMISSED,
    description: 'When a banner is dismissed',
    attributes: [
      EventAttributes.BANNER_END_REASON,
      EventAttributes.BANNER_ID,
      EventAttributes.BANNER_NAME,
      EventAttributes.BANNER_SESSION_ID,
      EventAttributes.BANNER_VERSION_ID,
      EventAttributes.BANNER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Resource Center Started',
    codeName: BizEvents.RESOURCE_CENTER_STARTED,
    description: 'When a Resource Center session starts',
    attributes: [
      EventAttributes.RESOURCE_CENTER_ID,
      EventAttributes.RESOURCE_CENTER_NAME,
      EventAttributes.RESOURCE_CENTER_SESSION_ID,
      EventAttributes.RESOURCE_CENTER_START_REASON,
      EventAttributes.RESOURCE_CENTER_VERSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Resource Center Opened',
    codeName: BizEvents.RESOURCE_CENTER_OPENED,
    description: 'When the Resource Center panel is opened',
    attributes: [
      EventAttributes.RESOURCE_CENTER_ID,
      EventAttributes.RESOURCE_CENTER_NAME,
      EventAttributes.RESOURCE_CENTER_SESSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Resource Center Closed',
    codeName: BizEvents.RESOURCE_CENTER_CLOSED,
    description: 'When the Resource Center panel is closed',
    attributes: [
      EventAttributes.RESOURCE_CENTER_ID,
      EventAttributes.RESOURCE_CENTER_NAME,
      EventAttributes.RESOURCE_CENTER_SESSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Resource Center Clicked',
    codeName: BizEvents.RESOURCE_CENTER_CLICKED,
    description: 'When a block inside the Resource Center is clicked',
    attributes: [
      EventAttributes.RESOURCE_CENTER_ID,
      EventAttributes.RESOURCE_CENTER_NAME,
      EventAttributes.RESOURCE_CENTER_SESSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_NUMBER,
      EventAttributes.RESOURCE_CENTER_TAB_ID,
      EventAttributes.RESOURCE_CENTER_TAB_NAME,
      EventAttributes.RESOURCE_CENTER_BLOCK_ID,
      EventAttributes.RESOURCE_CENTER_BLOCK_NAME,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Resource Center Dismissed',
    codeName: BizEvents.RESOURCE_CENTER_DISMISSED,
    description: 'When the Resource Center session is dismissed',
    attributes: [
      EventAttributes.RESOURCE_CENTER_END_REASON,
      EventAttributes.RESOURCE_CENTER_ID,
      EventAttributes.RESOURCE_CENTER_NAME,
      EventAttributes.RESOURCE_CENTER_SESSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_ID,
      EventAttributes.RESOURCE_CENTER_VERSION_NUMBER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Question Answered',
    codeName: BizEvents.QUESTION_ANSWERED,
    description: 'When a survey question is answered',
    attributes: [
      EventAttributes.FLOW_ID,
      EventAttributes.FLOW_NAME,
      EventAttributes.FLOW_VERSION_ID,
      EventAttributes.FLOW_VERSION_NUMBER,
      EventAttributes.LIST_ANSWER,
      EventAttributes.NUMBER_ANSWER,
      EventAttributes.QUESTION_CVID,
      EventAttributes.QUESTION_NAME,
      EventAttributes.QUESTION_TYPE,
      EventAttributes.TEXT_ANSWER,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Checklist Completed',
    codeName: BizEvents.CHECKLIST_COMPLETED,
    description: 'When all checklist tasks are complete',
    attributes: [
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
      EventAttributes.CHECKLIST_ID,
      EventAttributes.CHECKLIST_NAME,
      EventAttributes.CHECKLIST_SESSION_ID,
      EventAttributes.CHECKLIST_VERSION_ID,
      EventAttributes.CHECKLIST_VERSION_NUMBER,
    ],
  },
  {
    displayName: 'Checklist Dismissed/Ended',
    codeName: BizEvents.CHECKLIST_DISMISSED,
    description: 'When a checklist is dismissed',
    attributes: [
      EventAttributes.CHECKLIST_END_REASON,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
      EventAttributes.CHECKLIST_VERSION_NUMBER,
      EventAttributes.CHECKLIST_ID,
      EventAttributes.CHECKLIST_NAME,
      EventAttributes.CHECKLIST_SESSION_ID,
      EventAttributes.CHECKLIST_VERSION_ID,
    ],
  },
  {
    displayName: 'Checklist Hidden',
    codeName: BizEvents.CHECKLIST_HIDDEN,
    description: 'When the checklist panel is collapsed to its launcher',
    attributes: [
      EventAttributes.CHECKLIST_VERSION_NUMBER,
      EventAttributes.CHECKLIST_NAME,
      EventAttributes.CHECKLIST_ID,
      EventAttributes.CHECKLIST_SESSION_ID,
      EventAttributes.CHECKLIST_VERSION_ID,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
      EventAttributes.PAGE_URL,
      EventAttributes.LOCALE_CODE,
    ],
  },
  {
    displayName: 'Checklist Shown',
    codeName: BizEvents.CHECKLIST_SEEN,
    description: 'When the checklist panel is expanded',
    attributes: [
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.LOCALE_CODE,
      EventAttributes.CHECKLIST_ID,
      EventAttributes.CHECKLIST_VERSION_NUMBER,
      EventAttributes.CHECKLIST_SESSION_ID,
      EventAttributes.CHECKLIST_VERSION_ID,
      EventAttributes.CHECKLIST_NAME,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Checklist Started',
    codeName: BizEvents.CHECKLIST_STARTED,
    description: 'When a checklist session starts',
    attributes: [
      EventAttributes.VIEWPORT_WIDTH,
      EventAttributes.LOCALE_CODE,
      EventAttributes.CHECKLIST_VERSION_NUMBER,
      EventAttributes.CHECKLIST_VERSION_ID,
      EventAttributes.CHECKLIST_START_REASON,
      EventAttributes.CHECKLIST_SESSION_ID,
      EventAttributes.CHECKLIST_NAME,
      EventAttributes.CHECKLIST_ID,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.PAGE_URL,
    ],
  },
  {
    displayName: 'Checklist Task Clicked',
    codeName: BizEvents.CHECKLIST_TASK_CLICKED,
    description: 'When a checklist task is clicked',
    attributes: [
      EventAttributes.CHECKLIST_SESSION_ID,
      EventAttributes.CHECKLIST_NAME,
      EventAttributes.CHECKLIST_TASK_ID,
      EventAttributes.CHECKLIST_TASK_CVID,
      EventAttributes.CHECKLIST_ID,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
      EventAttributes.PAGE_URL,
      EventAttributes.LOCALE_CODE,
      EventAttributes.CHECKLIST_VERSION_NUMBER,
      EventAttributes.CHECKLIST_VERSION_ID,
      EventAttributes.CHECKLIST_TASK_NAME,
    ],
  },
  {
    displayName: 'Announcement Seen',
    codeName: BizEvents.ANNOUNCEMENT_SEEN,
    attributes: [
      EventAttributes.ANNOUNCEMENT_ID,
      EventAttributes.ANNOUNCEMENT_NAME,
      EventAttributes.ANNOUNCEMENT_VERSION_ID,
      EventAttributes.ANNOUNCEMENT_VERSION_NUMBER,
      EventAttributes.ANNOUNCEMENT_LEVEL,
      EventAttributes.ANNOUNCEMENT_SOURCE,
      EventAttributes.LOCALE_CODE,
      EventAttributes.PAGE_URL,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
    ],
  },
  {
    displayName: 'Checklist Task Completed',
    codeName: BizEvents.CHECKLIST_TASK_COMPLETED,
    description: "When a checklist task's completion conditions are met",
    attributes: [
      EventAttributes.PAGE_URL,
      EventAttributes.CHECKLIST_VERSION_NUMBER,
      EventAttributes.CHECKLIST_VERSION_ID,
      EventAttributes.CHECKLIST_TASK_NAME,
      EventAttributes.CHECKLIST_TASK_ID,
      EventAttributes.CHECKLIST_TASK_CVID,
      EventAttributes.CHECKLIST_ID,
      EventAttributes.CHECKLIST_SESSION_ID,
      EventAttributes.CHECKLIST_NAME,
      EventAttributes.VIEWPORT_HEIGHT,
      EventAttributes.VIEWPORT_WIDTH,
      EventAttributes.LOCALE_CODE,
    ],
  },
];

export const defaultAttributes: ProjectDefaultAttribute[] = [
  {
    codeName: UserAttributes.EMAIL,
    displayName: 'Email',
    bizType: AttributeBizTypes.User,
    dataType: AttributeDataType.String,
    description: 'Email address belonging to the user',
  },
  {
    codeName: UserAttributes.NAME,
    displayName: 'Name',
    bizType: AttributeBizTypes.User,
    dataType: AttributeDataType.String,
    description: 'Full name of the user',
  },
  {
    codeName: UserAttributes.FIRST_SEEN_AT,
    displayName: 'First Seen',
    bizType: AttributeBizTypes.User,
    dataType: AttributeDataType.DateTime,
    description: 'When the user first interacted with Usertour',
  },
  {
    codeName: UserAttributes.LAST_SEEN_AT,
    displayName: 'Last Seen',
    bizType: AttributeBizTypes.User,
    dataType: AttributeDataType.DateTime,
    description: 'When the user most recently interacted with Usertour',
  },
  {
    codeName: UserAttributes.SIGNED_UP_AT,
    displayName: 'Signed Up',
    bizType: AttributeBizTypes.User,
    dataType: AttributeDataType.DateTime,
    description: 'When the user first signed up to your app',
  },
  {
    codeName: CompanyAttributes.NAME,
    displayName: 'Company Name',
    bizType: AttributeBizTypes.Company,
    dataType: AttributeDataType.String,
    description: 'Name of the company',
  },
  {
    codeName: CompanyAttributes.FIRST_SEEN_AT,
    displayName: 'Company First Seen',
    bizType: AttributeBizTypes.Company,
    dataType: AttributeDataType.DateTime,
    description: 'When any member of the company first appeared in Usertour',
  },
  {
    codeName: CompanyAttributes.LAST_SEEN_AT,
    displayName: 'Company Last Seen',
    bizType: AttributeBizTypes.Company,
    dataType: AttributeDataType.DateTime,
    description: 'When any member of the company most recently appeared in Usertour',
  },
  {
    codeName: CompanyAttributes.SIGNED_UP_AT,
    displayName: 'Company Signed Up',
    bizType: AttributeBizTypes.Company,
    dataType: AttributeDataType.DateTime,
    description: 'When the company first signed up to your app',
  },
  {
    codeName: EventAttributes.FLOW_ID,
    displayName: 'Flow ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour flow',
  },
  {
    codeName: EventAttributes.FLOW_NAME,
    displayName: 'Flow Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour flow',
  },
  {
    codeName: EventAttributes.FLOW_SESSION_ID,
    displayName: 'Flow Session ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: "A user's session viewing this flow",
  },
  {
    codeName: EventAttributes.FLOW_START_REASON,
    displayName: 'Flow Start Reason',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Why the flow started',
  },
  {
    codeName: EventAttributes.FLOW_END_REASON,
    displayName: 'Flow End Reason',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Why the flow ended',
  },
  {
    codeName: EventAttributes.FLOW_STEP_ID,
    displayName: 'Flow Step ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour flow step',
  },
  {
    codeName: EventAttributes.FLOW_STEP_CVID,
    displayName: 'Flow Step CVID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Cross-version identifier of the Usertour flow step',
  },
  {
    codeName: EventAttributes.FLOW_STEP_NAME,
    displayName: 'Flow Step Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour flow step',
  },
  {
    codeName: EventAttributes.FLOW_STEP_NUMBER,
    displayName: 'Flow Step Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Position of the Usertour flow step',
  },
  {
    codeName: EventAttributes.FLOW_STEP_PROGRESS,
    displayName: 'Flow Step Progress',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Progress percentage of the Usertour flow step toward its goal',
  },
  {
    codeName: EventAttributes.FLOW_VERSION_ID,
    displayName: 'Flow Version ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour flow version',
  },
  {
    codeName: EventAttributes.FLOW_VERSION_NUMBER,
    displayName: 'Flow Version Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Number of the Usertour flow version',
  },
  {
    codeName: EventAttributes.LAUNCHER_ID,
    displayName: 'Launcher ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour launcher',
  },
  {
    codeName: EventAttributes.LAUNCHER_NAME,
    displayName: 'Launcher Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour launcher',
  },
  {
    codeName: EventAttributes.LAUNCHER_SESSION_ID,
    displayName: 'Launcher Session ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: "A user's session viewing this launcher",
  },
  {
    codeName: EventAttributes.LAUNCHER_VERSION_ID,
    displayName: 'Launcher Version ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour launcher version',
  },
  {
    codeName: EventAttributes.LAUNCHER_VERSION_NUMBER,
    displayName: 'Launcher Version Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Number of the Usertour launcher version',
  },
  {
    codeName: EventAttributes.BANNER_ID,
    displayName: 'Banner ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour banner',
  },
  {
    codeName: EventAttributes.BANNER_NAME,
    displayName: 'Banner Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour banner',
  },
  {
    codeName: EventAttributes.BANNER_SESSION_ID,
    displayName: 'Banner Session ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: "A user's session viewing this banner",
  },
  {
    codeName: EventAttributes.BANNER_VERSION_ID,
    displayName: 'Banner Version ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour banner version',
  },
  {
    codeName: EventAttributes.BANNER_VERSION_NUMBER,
    displayName: 'Banner Version Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Number of the Usertour banner version',
  },
  {
    codeName: EventAttributes.BANNER_END_REASON,
    displayName: 'Banner End Reason',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Why the banner ended',
  },
  {
    codeName: EventAttributes.CHECKLIST_ID,
    displayName: 'Checklist ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour checklist',
  },
  {
    codeName: EventAttributes.CHECKLIST_NAME,
    displayName: 'Checklist Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour checklist',
  },
  {
    codeName: EventAttributes.CHECKLIST_SESSION_ID,
    displayName: 'Checklist Session ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: "A user's session viewing this checklist",
  },
  {
    codeName: EventAttributes.CHECKLIST_VERSION_ID,
    displayName: 'Checklist Version ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour checklist version',
  },
  {
    codeName: EventAttributes.CHECKLIST_VERSION_NUMBER,
    displayName: 'Checklist Version Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Number of the Usertour checklist version',
  },
  {
    codeName: EventAttributes.CHECKLIST_END_REASON,
    displayName: 'Checklist End Reason',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Why the checklist ended',
  },
  {
    codeName: EventAttributes.CHECKLIST_START_REASON,
    displayName: 'Checklist Start Reason',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Why the checklist started',
  },
  {
    codeName: EventAttributes.CHECKLIST_TASK_CVID,
    displayName: 'Checklist Task CVID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description:
      "Stable identifier of the Usertour checklist task that doesn't change across versions",
  },
  {
    codeName: EventAttributes.CHECKLIST_TASK_ID,
    displayName: 'Checklist Task ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour checklist task',
  },
  {
    codeName: EventAttributes.CHECKLIST_TASK_NAME,
    displayName: 'Checklist Task Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour checklist task',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_ID,
    displayName: 'Resource Center ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour resource center',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_NAME,
    displayName: 'Resource Center Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour resource center',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_SESSION_ID,
    displayName: 'Resource Center Session ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: "A user's session viewing this resource center",
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_VERSION_ID,
    displayName: 'Resource Center Version ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour resource center version',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_VERSION_NUMBER,
    displayName: 'Resource Center Version Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Number of the Usertour resource center version',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_BLOCK_ID,
    displayName: 'Resource Center Block ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour resource center block',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_BLOCK_NAME,
    displayName: 'Resource Center Block Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour resource center block',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_TAB_ID,
    displayName: 'Resource Center Tab ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour resource center tab the block belongs to',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_TAB_NAME,
    displayName: 'Resource Center Tab Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour resource center tab the block belongs to',
  },
  {
    codeName: EventAttributes.RESOURCE_CENTER_END_REASON,
    displayName: 'Resource Center End Reason',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Why the resource center ended',
  },
  {
    codeName: EventAttributes.EVENT_TRACKER_ID,
    displayName: 'Event Tracker ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour event tracker',
  },
  {
    codeName: EventAttributes.EVENT_TRACKER_NAME,
    displayName: 'Event Tracker Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour event tracker',
  },
  {
    codeName: EventAttributes.EVENT_TRACKER_VERSION_ID,
    displayName: 'Event Tracker Version ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour event tracker version',
  },
  {
    codeName: EventAttributes.EVENT_TRACKER_VERSION_NUMBER,
    displayName: 'Event Tracker Version Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Number of the Usertour event tracker version',
  },
  {
    codeName: EventAttributes.ANNOUNCEMENT_ID,
    displayName: 'Announcement ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour announcement',
  },
  {
    codeName: EventAttributes.ANNOUNCEMENT_NAME,
    displayName: 'Announcement Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the Usertour announcement',
  },
  {
    codeName: EventAttributes.ANNOUNCEMENT_VERSION_ID,
    displayName: 'Announcement Version ID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Unique identifier of the Usertour announcement version',
  },
  {
    codeName: EventAttributes.ANNOUNCEMENT_VERSION_NUMBER,
    displayName: 'Announcement Version Number',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Number of the Usertour announcement version',
  },
  {
    codeName: EventAttributes.ANNOUNCEMENT_LEVEL,
    displayName: 'Announcement Level',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'How the announcement was delivered (silent, badge, popup)',
  },
  {
    codeName: EventAttributes.ANNOUNCEMENT_SOURCE,
    displayName: 'Announcement Source',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Where the announcement was shown (e.g. resource_center)',
  },
  {
    codeName: EventAttributes.LIST_ANSWER,
    displayName: 'List Answer',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.List,
    description: 'Option(s) chosen from the available list',
  },
  {
    codeName: EventAttributes.NUMBER_ANSWER,
    displayName: 'Number Answer',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Numeric value submitted as the answer',
  },
  {
    codeName: EventAttributes.TEXT_ANSWER,
    displayName: 'Text Answer',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Text value submitted as the answer',
  },
  {
    codeName: EventAttributes.LOCALE_CODE,
    displayName: 'Locale Code',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Language/locale code associated with the content',
  },
  {
    codeName: EventAttributes.PAGE_URL,
    displayName: 'Page URL',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'URL of the page on which the event was triggered',
  },
  {
    codeName: EventAttributes.VIEWPORT_HEIGHT,
    displayName: 'Viewport Height',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Browser viewport height measured in pixels',
  },
  {
    codeName: EventAttributes.VIEWPORT_WIDTH,
    displayName: 'Viewport Width',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.Number,
    description: 'Browser viewport width measured in pixels',
  },
  {
    codeName: EventAttributes.QUESTION_CVID,
    displayName: 'Question CVID',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: "Stable identifier of the question that doesn't change across versions",
  },
  {
    codeName: EventAttributes.QUESTION_NAME,
    displayName: 'Question Name',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Display name of the question',
  },
  {
    codeName: EventAttributes.QUESTION_TYPE,
    displayName: 'Question Type',
    bizType: AttributeBizTypes.Event,
    dataType: AttributeDataType.String,
    description: 'Type/category of the question',
  },
];
