/**
 * Theme settings validation constraints — the neutral, presentation-free single
 * source of truth for what a valid theme setting is and its bounds. Both the
 * theme builder (form-control bounds) and the server (write-validation zod)
 * derive from THIS, so neither owns the contract and they cannot drift.
 *
 * Scope: declarative STYLE values only. Media-asset fields (avatars, header image,
 * logo, custom launcher icon) are managed in the theme builder, not here. UI
 * concerns (labels, tooltips, widget choice, visibleWhen) also stay in the builder;
 * for enums the allowed *values* live here, their display *labels* in the builder.
 */
export type ThemeSettingConstraint =
  | { kind: 'number'; min?: number; max?: number }
  | { kind: 'color'; allowAuto: boolean }
  | { kind: 'enum'; values: readonly (string | number)[] }
  | { kind: 'boolean' }
  | { kind: 'string' };

export const THEME_SETTING_CONSTRAINTS = {
  'avatar.size': { kind: 'number', min: 24, max: 120 },
  'backdrop.color': { kind: 'color', allowAuto: false },
  'backdrop.highlight.color': { kind: 'color', allowAuto: false },
  'backdrop.highlight.opacity': { kind: 'number', min: 0, max: 100 },
  'backdrop.highlight.radius': { kind: 'number', min: 0, max: 40 },
  'backdrop.highlight.spread': { kind: 'number', min: 0, max: 40 },
  'backdrop.highlight.type': { kind: 'enum', values: ['outside', 'inside'] },
  'backdrop.opacity': { kind: 'number', min: 0, max: 100 },
  'banner.animationDuration': { kind: 'number', min: 0, max: 1000 },
  'banner.animationTiming': { kind: 'enum', values: ['smooth', 'snappy', 'gentle', 'linear'] },
  'banner.backgroundColor.background': { kind: 'color', allowAuto: true },
  'banner.padding': { kind: 'number', min: 0, max: 40 },
  'banner.textColor.color': { kind: 'color', allowAuto: true },
  'border.borderColor': { kind: 'color', allowAuto: true },
  'border.borderRadius': { kind: 'number', min: 0, max: 40 },
  'border.borderWidth': { kind: 'number', min: 0, max: 10 },
  'border.borderWidthEnabled': { kind: 'boolean' },
  'brandColor.active': { kind: 'color', allowAuto: true },
  'brandColor.background': { kind: 'color', allowAuto: false },
  'brandColor.color': { kind: 'color', allowAuto: false },
  'brandColor.hover': { kind: 'color', allowAuto: true },
  'bubble.placement.position': {
    kind: 'enum',
    values: [
      'leftTop',
      'centerTop',
      'rightTop',
      'leftBottom',
      'centerBottom',
      'rightBottom',
      'center',
    ],
  },
  'bubble.placement.positionOffsetX': { kind: 'number' },
  'bubble.placement.positionOffsetY': { kind: 'number' },
  'bubble.width': { kind: 'number', min: 200, max: 600 },
  'buttons.borderRadius': { kind: 'number', min: 0, max: 32 },
  'buttons.height': { kind: 'number', min: 24, max: 64 },
  'buttons.minWidth': { kind: 'number', min: 0, max: 200 },
  'buttons.primary.backgroundColor.active': { kind: 'color', allowAuto: true },
  'buttons.primary.backgroundColor.background': { kind: 'color', allowAuto: true },
  'buttons.primary.backgroundColor.hover': { kind: 'color', allowAuto: true },
  'buttons.primary.border.borderWidth': { kind: 'number', min: 0, max: 10 },
  'buttons.primary.border.color.active': { kind: 'color', allowAuto: true },
  'buttons.primary.border.color.color': { kind: 'color', allowAuto: true },
  'buttons.primary.border.color.hover': { kind: 'color', allowAuto: true },
  'buttons.primary.border.enabled': { kind: 'boolean' },
  'buttons.primary.fontWeight': {
    kind: 'enum',
    values: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  'buttons.primary.textColor.active': { kind: 'color', allowAuto: true },
  'buttons.primary.textColor.color': { kind: 'color', allowAuto: true },
  'buttons.primary.textColor.hover': { kind: 'color', allowAuto: true },
  'buttons.px': { kind: 'number', min: 0, max: 40 },
  'buttons.secondary.backgroundColor.active': { kind: 'color', allowAuto: true },
  'buttons.secondary.backgroundColor.background': { kind: 'color', allowAuto: true },
  'buttons.secondary.backgroundColor.hover': { kind: 'color', allowAuto: true },
  'buttons.secondary.border.borderWidth': { kind: 'number', min: 0, max: 10 },
  'buttons.secondary.border.color.active': { kind: 'color', allowAuto: true },
  'buttons.secondary.border.color.color': { kind: 'color', allowAuto: true },
  'buttons.secondary.border.color.hover': { kind: 'color', allowAuto: true },
  'buttons.secondary.border.enabled': { kind: 'boolean' },
  'buttons.secondary.fontWeight': {
    kind: 'enum',
    values: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  'buttons.secondary.textColor.active': { kind: 'color', allowAuto: true },
  'buttons.secondary.textColor.color': { kind: 'color', allowAuto: true },
  'buttons.secondary.textColor.hover': { kind: 'color', allowAuto: true },
  'checklist.checkmarkColor': { kind: 'color', allowAuto: true },
  'checklist.completedTaskTextDecoration': { kind: 'enum', values: ['none', 'line-through'] },
  'checklist.placement.position': {
    kind: 'enum',
    values: ['leftTop', 'rightTop', 'leftBottom', 'rightBottom', 'center'],
  },
  'checklist.placement.positionOffsetX': { kind: 'number' },
  'checklist.placement.positionOffsetY': { kind: 'number' },
  'checklist.width': { kind: 'number', min: 240, max: 600 },
  'checklist.zIndex': { kind: 'number' },
  'checklistLauncher.borderRadius': { kind: 'number', min: 0, max: 40 },
  'checklistLauncher.color.active': { kind: 'color', allowAuto: true },
  'checklistLauncher.color.background': { kind: 'color', allowAuto: true },
  'checklistLauncher.color.color': { kind: 'color', allowAuto: true },
  'checklistLauncher.color.hover': { kind: 'color', allowAuto: true },
  'checklistLauncher.counter.background': { kind: 'color', allowAuto: true },
  'checklistLauncher.counter.color': { kind: 'color', allowAuto: true },
  'checklistLauncher.fontWeight': {
    kind: 'enum',
    values: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  'checklistLauncher.height': { kind: 'number', min: 32, max: 80 },
  'checklistLauncher.placement.position': {
    kind: 'enum',
    values: ['leftTop', 'rightTop', 'leftBottom', 'rightBottom', 'center'],
  },
  'checklistLauncher.placement.positionOffsetX': { kind: 'number' },
  'checklistLauncher.placement.positionOffsetY': { kind: 'number' },
  customCss: { kind: 'string' },
  'focusHighlight.color': { kind: 'color', allowAuto: true },
  'focusHighlight.opacity': { kind: 'number', min: 0, max: 100 },
  'font.customFontFamily': { kind: 'string' },
  'font.fontFamily': { kind: 'string' },
  'font.fontSize': { kind: 'number', min: 10, max: 24 },
  'font.fontWeightBold': { kind: 'enum', values: [100, 200, 300, 400, 500, 600, 700, 800, 900] },
  'font.fontWeightNormal': { kind: 'enum', values: [100, 200, 300, 400, 500, 600, 700, 800, 900] },
  'font.h1FontSize': { kind: 'number', min: 16, max: 48 },
  'font.h2FontSize': { kind: 'number', min: 14, max: 32 },
  'font.lineHeight': { kind: 'number', min: 12, max: 40 },
  'font.linkColor': { kind: 'color', allowAuto: true },
  'launcherBeacon.color': { kind: 'color', allowAuto: true },
  'launcherBeacon.size': { kind: 'number', min: 8, max: 32 },
  'launcherButtons.borderRadius': { kind: 'number', min: 0, max: 40 },
  'launcherButtons.height': { kind: 'number', min: 24, max: 80 },
  'launcherButtons.primary.backgroundColor.active': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.backgroundColor.background': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.backgroundColor.hover': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.border.borderWidth': { kind: 'number', min: 0, max: 10 },
  'launcherButtons.primary.border.color.active': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.border.color.color': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.border.color.hover': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.border.enabled': { kind: 'boolean' },
  'launcherButtons.primary.fontWeight': {
    kind: 'enum',
    values: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  'launcherButtons.primary.textColor.active': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.textColor.color': { kind: 'color', allowAuto: true },
  'launcherButtons.primary.textColor.hover': { kind: 'color', allowAuto: true },
  'launcherButtons.px': { kind: 'number', min: 0, max: 40 },
  'launcherButtons.width': { kind: 'number', min: 0, max: 400 },
  'launcherIcon.color.active': { kind: 'color', allowAuto: true },
  'launcherIcon.color.color': { kind: 'color', allowAuto: true },
  'launcherIcon.color.hover': { kind: 'color', allowAuto: true },
  'launcherIcon.opacity': { kind: 'number', min: 0, max: 100 },
  'launcherIcon.size': { kind: 'number', min: 8, max: 64 },
  'mainColor.active': { kind: 'color', allowAuto: true },
  'mainColor.background': { kind: 'color', allowAuto: false },
  'mainColor.color': { kind: 'color', allowAuto: false },
  'mainColor.hover': { kind: 'color', allowAuto: true },
  'modal.backdropClickBehavior': { kind: 'enum', values: ['do-nothing', 'dismiss-flow'] },
  'modal.padding': { kind: 'number', min: 0, max: 80 },
  'modal.width': { kind: 'number', min: 320, max: 1200 },
  'progress.chainRoundedHeight': { kind: 'number', min: 1, max: 50 },
  'progress.chainSquaredHeight': { kind: 'number', min: 1, max: 50 },
  'progress.color': { kind: 'color', allowAuto: true },
  'progress.dotsHeight': { kind: 'number', min: 1, max: 50 },
  'progress.enabled': { kind: 'boolean' },
  'progress.height': { kind: 'number', min: 1, max: 50 },
  'progress.narrowHeight': { kind: 'number', min: 1, max: 50 },
  'progress.numberedHeight': { kind: 'number', min: 1, max: 50 },
  'progress.position': { kind: 'enum', values: ['top', 'bottom'] },
  'progress.type': {
    kind: 'enum',
    values: ['full-width', 'narrow', 'chain-rounded', 'chain-squared', 'dots', 'numbered'],
  },
  'resourceCenter.headerBackground.color': { kind: 'color', allowAuto: true },
  'resourceCenter.headerBackground.gradientFrom': { kind: 'color', allowAuto: true },
  'resourceCenter.headerBackground.gradientTo': { kind: 'color', allowAuto: true },
  'resourceCenter.headerBackground.type': {
    kind: 'enum',
    values: ['none', 'color', 'gradient', 'image'],
  },
  'resourceCenter.largeWidth': { kind: 'number', min: 320, max: 800 },
  'resourceCenter.maxHeight': { kind: 'number', min: 200, max: 1200 },
  'resourceCenter.normalWidth': { kind: 'number', min: 240, max: 600 },
  'resourceCenter.offsetX': { kind: 'number', min: 0, max: 200 },
  'resourceCenter.offsetY': { kind: 'number', min: 0, max: 200 },
  'resourceCenter.placement': {
    kind: 'enum',
    values: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
  },
  'resourceCenter.transitionDuration': { kind: 'number', min: 0, max: 1000 },
  'resourceCenter.zIndex': { kind: 'number' },
  'resourceCenterLauncherButton.borderRadius': { kind: 'number', min: 0, max: 40 },
  'resourceCenterLauncherButton.color.active': { kind: 'color', allowAuto: true },
  'resourceCenterLauncherButton.color.background': { kind: 'color', allowAuto: true },
  'resourceCenterLauncherButton.color.foreground': { kind: 'color', allowAuto: true },
  'resourceCenterLauncherButton.color.hover': { kind: 'color', allowAuto: true },
  'resourceCenterLauncherButton.height': { kind: 'number', min: 24, max: 80 },
  'resourceCenterLauncherButton.iconType': {
    kind: 'enum',
    values: ['default-question-mark', 'plaintext-question-mark', 'custom'],
  },
  'resourceCenterLauncherButton.imageHeight': { kind: 'number', min: 16, max: 80 },
  'resourceCenterLauncherButton.textMode': {
    kind: 'enum',
    values: ['resource-center-text', 'no-text'],
  },
  'survey.color': { kind: 'color', allowAuto: true },
  'tooltip.missingTargetBehavior': { kind: 'enum', values: ['auto-dismiss', 'use-bubble'] },
  'tooltip.missingTargetTolerance': { kind: 'number', min: 0, max: 10 },
  'tooltip.notchSize': { kind: 'number', min: 0, max: 30 },
  'tooltip.width': { kind: 'number', min: 200, max: 600 },
  'xbutton.color': { kind: 'color', allowAuto: true },
} as const satisfies Record<string, ThemeSettingConstraint>;

export type ThemeSettingPath = keyof typeof THEME_SETTING_CONSTRAINTS;
