import { ThemeDetailPreviewType } from '@usertour/types';
import type { BuilderSection, FieldDef } from './types';

// Helpers ------------------------------------------------------------------

const colorGroup4 = (prefix: string, label: string): FieldDef[] => [
  { type: 'color', path: `${prefix}.background`, label: `${label} background` },
  { type: 'color', path: `${prefix}.color`, label: `${label} color` },
  { type: 'color', path: `${prefix}.hover`, label: `${label} hover`, allowAuto: true },
  { type: 'color', path: `${prefix}.active`, label: `${label} active`, allowAuto: true },
];

const colorGroup6 = (prefix: string, label: string): FieldDef[] => [
  ...colorGroup4(prefix, label),
  { type: 'color', path: `${prefix}.autoHover`, label: `${label} auto hover` },
  { type: 'color', path: `${prefix}.autoActive`, label: `${label} auto active` },
];

const buttonFields = (prefix: string): FieldDef[] => [
  {
    type: 'number',
    path: `${prefix}.fontWeight`,
    label: 'Font weight',
    min: 100,
    max: 900,
    step: 100,
  },
  ...colorGroup4(`${prefix}.textColor`, 'Text'),
  ...colorGroup4(`${prefix}.backgroundColor`, 'Background'),
  { type: 'boolean', path: `${prefix}.border.enabled`, label: 'Show border' },
  {
    type: 'number',
    path: `${prefix}.border.borderWidth`,
    label: 'Border width',
    min: 0,
    max: 10,
    suffix: 'px',
  },
  ...colorGroup4(`${prefix}.border.color`, 'Border'),
];

// Sections — order and labels match v1's accordion -------------------------

export const builderSections: BuilderSection[] = [
  {
    id: 'base-colors',
    label: 'Base colors',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [...colorGroup6('brandColor', 'Brand'), ...colorGroup6('mainColor', 'Main')],
  },
  {
    id: 'avatar',
    label: 'Avatar',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      {
        type: 'select',
        path: 'avatar.type',
        label: 'Type',
        options: [
          { value: 'cartoon', label: 'Cartoon' },
          { value: 'upload', label: 'Upload' },
          { value: 'url', label: 'URL' },
          { value: 'none', label: 'None' },
        ],
      },
      { type: 'number', path: 'avatar.size', label: 'Size', min: 24, max: 120, suffix: 'px' },
      { type: 'text', path: 'avatar.url', label: 'URL' },
      { type: 'text', path: 'avatar.name', label: 'Name' },
    ],
  },
  {
    id: 'font',
    label: 'Font',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      { type: 'font-family', path: 'font.fontFamily', label: 'Font family' },
      {
        type: 'number',
        path: 'font.fontSize',
        label: 'Body size',
        min: 10,
        max: 24,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'font.lineHeight',
        label: 'Line height',
        min: 12,
        max: 40,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'font.fontWeightNormal',
        label: 'Body weight',
        min: 100,
        max: 900,
        step: 100,
      },
      {
        type: 'number',
        path: 'font.fontWeightBold',
        label: 'Bold weight',
        min: 100,
        max: 900,
        step: 100,
      },
      {
        type: 'number',
        path: 'font.h1FontSize',
        label: 'H1 size',
        min: 16,
        max: 48,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'font.h2FontSize',
        label: 'H2 size',
        min: 14,
        max: 32,
        suffix: 'px',
      },
      { type: 'color', path: 'font.linkColor', label: 'Link color', allowAuto: true },
    ],
  },
  {
    id: 'chrome-border',
    label: 'Chrome border',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      { type: 'text', path: 'border.borderRadius', label: 'Radius' },
      { type: 'boolean', path: 'border.borderWidthEnabled', label: 'Show border' },
      {
        type: 'number',
        path: 'border.borderWidth',
        label: 'Border width',
        min: 0,
        max: 10,
        suffix: 'px',
      },
      { type: 'color', path: 'border.borderColor', label: 'Border color', allowAuto: true },
    ],
  },
  {
    id: 'x-button',
    label: 'X Button',
    previewWidget: ThemeDetailPreviewType.MODAL,
    fields: [{ type: 'color', path: 'xbutton.color', label: 'Color', allowAuto: true }],
  },
  {
    id: 'progress-bar',
    label: 'Progress bar',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      { type: 'boolean', path: 'progress.enabled', label: 'Show progress' },
      { type: 'color', path: 'progress.color', label: 'Color', allowAuto: true },
      {
        type: 'number',
        path: 'progress.height',
        label: 'Height',
        min: 1,
        max: 20,
        suffix: 'px',
      },
      {
        type: 'select',
        path: 'progress.type',
        label: 'Type',
        options: [
          { value: 'full-width', label: 'Full width' },
          { value: 'narrow', label: 'Narrow' },
          { value: 'chain-rounded', label: 'Chain rounded' },
          { value: 'chain-squared', label: 'Chain squared' },
          { value: 'dots', label: 'Dots' },
          { value: 'numbered', label: 'Numbered' },
        ],
      },
      {
        type: 'select',
        path: 'progress.position',
        label: 'Position',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'bottom', label: 'Bottom' },
        ],
      },
      {
        type: 'number',
        path: 'progress.narrowHeight',
        label: 'Narrow height',
        min: 1,
        max: 20,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'progress.chainSquaredHeight',
        label: 'Chain squared height',
        min: 1,
        max: 20,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'progress.chainRoundedHeight',
        label: 'Chain rounded height',
        min: 1,
        max: 20,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'progress.dotsHeight',
        label: 'Dots height',
        min: 1,
        max: 20,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'progress.numberedHeight',
        label: 'Numbered height',
        min: 1,
        max: 30,
        suffix: 'px',
      },
    ],
  },
  {
    id: 'buttons',
    label: 'Buttons',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      // shared
      { type: 'number', path: 'buttons.height', label: 'Height', min: 24, max: 64, suffix: 'px' },
      {
        type: 'number',
        path: 'buttons.minWidth',
        label: 'Min width',
        min: 0,
        max: 200,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'buttons.px',
        label: 'Horizontal padding',
        min: 0,
        max: 40,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'buttons.borderRadius',
        label: 'Border radius',
        min: 0,
        max: 32,
        suffix: 'px',
      },
      // primary + secondary
      ...buttonFields('buttons.primary'),
      ...buttonFields('buttons.secondary'),
    ],
  },
  {
    id: 'speech-bubble',
    label: 'Speech bubble',
    previewWidget: ThemeDetailPreviewType.BUBBLE,
    fields: [
      { type: 'number', path: 'bubble.width', label: 'Width', min: 200, max: 600, suffix: 'px' },
      { type: 'placement', path: 'bubble.placement', label: 'Placement' },
    ],
  },
  {
    id: 'tooltip',
    label: 'Tooltip',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      { type: 'number', path: 'tooltip.width', label: 'Width', min: 200, max: 600, suffix: 'px' },
      {
        type: 'number',
        path: 'tooltip.notchSize',
        label: 'Notch size',
        min: 0,
        max: 30,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'tooltip.missingTargetTolerance',
        label: 'Missing target tolerance',
        min: 0,
        max: 60,
        suffix: 's',
      },
      {
        type: 'select',
        path: 'tooltip.missingTargetBehavior',
        label: 'Missing target behavior',
        options: [
          { value: 'auto-dismiss', label: 'Auto dismiss' },
          { value: 'use-bubble', label: 'Use bubble' },
        ],
      },
    ],
  },
  {
    id: 'modal',
    label: 'Modal',
    previewWidget: ThemeDetailPreviewType.MODAL,
    fields: [
      { type: 'number', path: 'modal.width', label: 'Width', min: 320, max: 1200, suffix: 'px' },
      { type: 'number', path: 'modal.padding', label: 'Padding', min: 0, max: 80, suffix: 'px' },
      {
        type: 'select',
        path: 'modal.backdropClickBehavior',
        label: 'Backdrop click',
        options: [
          { value: 'do-nothing', label: 'Do nothing' },
          { value: 'dismiss-flow', label: 'Dismiss flow' },
        ],
      },
    ],
  },
  {
    id: 'survey',
    label: 'Survey',
    previewWidget: ThemeDetailPreviewType.NPS,
    fields: [{ type: 'color', path: 'survey.color', label: 'Color', allowAuto: true }],
  },
  {
    id: 'banner',
    label: 'Banner',
    previewWidget: ThemeDetailPreviewType.BANNER,
    fields: [
      ...colorGroup4('banner.backgroundColor', 'Background'),
      ...colorGroup4('banner.textColor', 'Text'),
      { type: 'number', path: 'banner.padding', label: 'Padding', min: 0, max: 40, suffix: 'px' },
      {
        type: 'number',
        path: 'banner.animationDuration',
        label: 'Animation duration',
        min: 0,
        max: 1000,
        suffix: 'ms',
      },
      {
        type: 'select',
        path: 'banner.animationTiming',
        label: 'Animation timing',
        options: [
          { value: 'smooth', label: 'Smooth' },
          { value: 'snappy', label: 'Snappy' },
          { value: 'gentle', label: 'Gentle' },
          { value: 'linear', label: 'Linear' },
        ],
      },
    ],
  },
  {
    id: 'checklist',
    label: 'Checklist',
    previewWidget: ThemeDetailPreviewType.CHECKLIST,
    fields: [
      { type: 'color', path: 'checklist.checkmarkColor', label: 'Checkmark color' },
      {
        type: 'number',
        path: 'checklist.width',
        label: 'Width',
        min: 240,
        max: 600,
        suffix: 'px',
      },
      { type: 'placement', path: 'checklist.placement', label: 'Placement' },
      { type: 'number', path: 'checklist.zIndex', label: 'z-index', min: 0, max: 100000 },
      {
        type: 'text',
        path: 'checklist.completedTaskTextDecoration',
        label: 'Completed task text decoration',
      },
    ],
  },
  {
    id: 'checklist-launcher',
    label: 'Checklist launcher',
    previewWidget: ThemeDetailPreviewType.CHECKLIST_LAUNCHER,
    fields: [
      {
        type: 'number',
        path: 'checklistLauncher.borderRadius',
        label: 'Border radius',
        min: 0,
        max: 40,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'checklistLauncher.height',
        label: 'Height',
        min: 32,
        max: 80,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'checklistLauncher.fontWeight',
        label: 'Font weight',
        min: 100,
        max: 900,
        step: 100,
      },
      { type: 'placement', path: 'checklistLauncher.placement', label: 'Placement' },
      ...colorGroup4('checklistLauncher.color', 'Launcher'),
      { type: 'color', path: 'checklistLauncher.counter.color', label: 'Counter color' },
      { type: 'color', path: 'checklistLauncher.counter.background', label: 'Counter background' },
    ],
  },
  {
    id: 'resource-center',
    label: 'Resource center',
    previewWidget: ThemeDetailPreviewType.RESOURCE_CENTER,
    fields: [
      // layout
      {
        type: 'select',
        path: 'resourceCenter.placement',
        label: 'Placement',
        options: [
          { value: 'top-left', label: 'Top left' },
          { value: 'top-right', label: 'Top right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
      {
        type: 'number',
        path: 'resourceCenter.offsetX',
        label: 'Offset X',
        min: 0,
        max: 200,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'resourceCenter.offsetY',
        label: 'Offset Y',
        min: 0,
        max: 200,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'resourceCenter.normalWidth',
        label: 'Normal width',
        min: 240,
        max: 600,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'resourceCenter.largeWidth',
        label: 'Large width',
        min: 320,
        max: 800,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'resourceCenter.maxHeight',
        label: 'Max height',
        min: 200,
        max: 1200,
        suffix: 'px',
      },
      { type: 'number', path: 'resourceCenter.zIndex', label: 'z-index', min: 0, max: 100000 },
      {
        type: 'number',
        path: 'resourceCenter.transitionDuration',
        label: 'Transition duration',
        min: 0,
        max: 1000,
        suffix: 'ms',
      },
      { type: 'boolean', path: 'resourceCenter.dividerLines', label: 'Divider lines' },
      { type: 'text', path: 'resourceCenter.logoUrl', label: 'Logo URL' },
      // header
      {
        type: 'select',
        path: 'resourceCenter.headerBackground.type',
        label: 'Header type',
        options: [
          { value: 'none', label: 'None' },
          { value: 'color', label: 'Color' },
          { value: 'gradient', label: 'Gradient' },
          { value: 'image', label: 'Image' },
        ],
      },
      {
        type: 'color',
        path: 'resourceCenter.headerBackground.color',
        label: 'Header color',
        allowAuto: true,
      },
      {
        type: 'color',
        path: 'resourceCenter.headerBackground.gradientFrom',
        label: 'Gradient from',
        allowAuto: true,
      },
      {
        type: 'color',
        path: 'resourceCenter.headerBackground.gradientTo',
        label: 'Gradient to',
        allowAuto: true,
      },
      { type: 'text', path: 'resourceCenter.headerBackground.imageUrl', label: 'Header image URL' },
    ],
  },
  {
    id: 'resource-center-launcher',
    label: 'Resource center launcher',
    previewWidget: ThemeDetailPreviewType.RESOURCE_CENTER_LAUNCHER,
    fields: [
      {
        type: 'select',
        path: 'resourceCenterLauncherButton.iconType',
        label: 'Icon type',
        options: [
          { value: 'default-question-mark', label: 'Default question mark' },
          { value: 'plaintext-question-mark', label: 'Plaintext question mark' },
          { value: 'custom', label: 'Custom' },
        ],
      },
      { type: 'text', path: 'resourceCenterLauncherButton.iconUrl', label: 'Icon URL' },
      {
        type: 'number',
        path: 'resourceCenterLauncherButton.height',
        label: 'Height',
        min: 24,
        max: 80,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'resourceCenterLauncherButton.imageHeight',
        label: 'Image height',
        min: 16,
        max: 80,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'resourceCenterLauncherButton.borderRadius',
        label: 'Border radius',
        min: 0,
        max: 40,
        suffix: 'px',
      },
      {
        type: 'select',
        path: 'resourceCenterLauncherButton.textMode',
        label: 'Text mode',
        options: [
          { value: 'resource-center-text', label: 'Resource center text' },
          { value: 'no-text', label: 'No text' },
        ],
      },
      {
        type: 'color',
        path: 'resourceCenterLauncherButton.color.background',
        label: 'Background',
        allowAuto: true,
      },
      {
        type: 'color',
        path: 'resourceCenterLauncherButton.color.hover',
        label: 'Hover',
        allowAuto: true,
      },
      {
        type: 'color',
        path: 'resourceCenterLauncherButton.color.active',
        label: 'Active',
        allowAuto: true,
      },
      {
        type: 'color',
        path: 'resourceCenterLauncherButton.color.foreground',
        label: 'Foreground',
        allowAuto: true,
      },
    ],
  },
  {
    id: 'launcher-beacons',
    label: 'Launcher beacons',
    previewWidget: ThemeDetailPreviewType.LAUNCHER_BEACON,
    fields: [
      { type: 'color', path: 'launcherBeacon.color', label: 'Color' },
      {
        type: 'number',
        path: 'launcherBeacon.size',
        label: 'Size',
        min: 8,
        max: 32,
        suffix: 'px',
      },
    ],
  },
  {
    id: 'launcher-icons',
    label: 'Launcher icons',
    previewWidget: ThemeDetailPreviewType.LAUNCHER_ICON,
    fields: [
      ...colorGroup4('launcherIcon.color', 'Icon'),
      {
        type: 'slider',
        path: 'launcherIcon.opacity',
        label: 'Opacity',
        min: 0,
        max: 100,
        suffix: '%',
      },
      {
        type: 'number',
        path: 'launcherIcon.size',
        label: 'Size',
        min: 8,
        max: 64,
        suffix: 'px',
      },
    ],
  },
  {
    id: 'launcher-buttons',
    label: 'Launcher buttons',
    previewWidget: ThemeDetailPreviewType.LAUNCHER_BUTTON,
    fields: [
      {
        type: 'number',
        path: 'launcherButtons.height',
        label: 'Height',
        min: 24,
        max: 80,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'launcherButtons.width',
        label: 'Width',
        min: 0,
        max: 400,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'launcherButtons.px',
        label: 'Horizontal padding',
        min: 0,
        max: 40,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'launcherButtons.borderRadius',
        label: 'Border radius',
        min: 0,
        max: 40,
        suffix: 'px',
      },
      ...buttonFields('launcherButtons.primary'),
    ],
  },
  {
    id: 'backdrop',
    label: 'Backdrop',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      { type: 'color', path: 'backdrop.color', label: 'Color' },
      {
        type: 'slider',
        path: 'backdrop.opacity',
        label: 'Opacity',
        min: 0,
        max: 100,
        suffix: '%',
      },
      { type: 'text', path: 'backdrop.highlight.type', label: 'Highlight type' },
      {
        type: 'number',
        path: 'backdrop.highlight.radius',
        label: 'Highlight radius',
        min: 0,
        max: 40,
        suffix: 'px',
      },
      {
        type: 'number',
        path: 'backdrop.highlight.spread',
        label: 'Highlight spread',
        min: 0,
        max: 40,
        suffix: 'px',
      },
      { type: 'color', path: 'backdrop.highlight.color', label: 'Highlight color' },
      {
        type: 'slider',
        path: 'backdrop.highlight.opacity',
        label: 'Highlight opacity',
        min: 0,
        max: 100,
        suffix: '%',
      },
    ],
  },
  {
    id: 'focus-highlight',
    label: 'Focus highlight',
    previewWidget: ThemeDetailPreviewType.TOOLTIP,
    fields: [
      { type: 'color', path: 'focusHighlight.color', label: 'Color', allowAuto: true },
      {
        type: 'slider',
        path: 'focusHighlight.opacity',
        label: 'Opacity',
        min: 0,
        max: 100,
        suffix: '%',
      },
    ],
  },
];
