/**
 * In-band authoring guide returned by the `get_authoring_guide` MCP tool. It
 * collects the cross-cutting conventions an agent needs to build *usable*
 * content on the first try — the things that don't fit in a single field's
 * description and that the `validate_content_version` / publish gate would
 * otherwise only reveal after a failure. Keep it in sync with the usability
 * validator and the representation schema.
 */
export const AUTHORING_GUIDE = `# Authoring Usertour content

## Lifecycle
1. \`create_content\` — pick a \`type\` and a \`themeId\` (see Themes). Returns the content + its draft \`editedVersionId\`. Non-flow types are seeded with their default \`data\`, so you only set the fields you care about.
2. \`update_content_version\` — write \`steps\` (flow) or \`data\` (other types) to that draft. **Top-level \`data\` fields merge** (omit one to leave it unchanged), **but any list you DO send replaces that whole list** — \`steps\`, or a data list like checklist \`items\`: omitted members are deleted (see Flow steps). The \`data\` arg is polymorphic (its shape depends on \`type\`), so the tool only types it as a generic object — call \`get_content_schema(type)\` for the exact \`data\` (or \`steps\`) JSON Schema before authoring.
3. \`validate_content_version\` — dry-run; returns \`{ ok, errors, warnings }\`. Fix \`errors\` first — but **read \`warnings\` too, even when \`ok:true\`**: they flag things that publish lets through but that silently misbehave (an orphan step nothing navigates to, a persistent surface with no start rules, a question bound to a missing attribute). \`ok\` only means "no blocking errors", not "correct".
4. \`publish_content\` — goes live. Requires \`contentId\` + \`versionId\`; \`environmentId\` defaults to the only environment when there is just one — with SEVERAL environments you must pass it (the tool errors and lists them rather than guessing). Publishing is **per environment** — to ship to several, call it once per \`environmentId\` (\`list_environments\` lists them). It REJECTS content that wouldn't render (same rules as validate).

**Editing published content** — a published version is read-only; writing to it fails with \`E0049\`. Call \`create_content_version\` to fork a fresh editable draft: it copies the steps/data and **preserves each step's \`cvid\`** (only the primary \`id\` is regenerated), so you can keep targeting steps by \`cvid\`/\`key\` without re-reading. Edit the draft, then validate and publish it. **Your edits are not live until you publish** — there is no separate "unsaved" flag; the signal that a separate editable draft EXISTS (whether or not its content actually differs from live — forking via \`create_content_version\` or \`restore_content_version\` flips it even before you edit anything) is \`editedVersionId\` ≠ the environment's \`publishedVersionId\` on \`get_content\`. Note \`diagnose_content\` always diagnoses the PUBLISHED version, so it can report green while a newer, unpublished draft sits waiting — after editing, publish (or you've changed nothing live).

## Themes (required)
Every visual type needs a theme or the SDK renders nothing. Call \`list_themes\` and pass a \`themeId\` to \`create_content\`; if unsure use the one with \`isDefault: true\`. \`create_theme\` starts from a fixed built-in default styling (a neutral base — NOT a copy of your project's default / \`isDefault\` theme, so don't read that theme to predict a new one's baseline); \`create_theme\` / \`update_theme\` accept a **partial \`settings\`** to brand it (colors, fonts, sizes, …): send only the fields you change — they're field-merged onto the current settings and "Auto" hover/active colors are derived server-side. The \`settings\` arg is a generic object on the tool; call \`get_theme_schema\` for the exact writable fields and their ranges before theming. It writes **style** values (colors, fonts, sizes, layout); **media assets** (avatars, header image, logo, custom icons) and conditional \`variations\` are set in the theme builder, not here.

**Color roles (what each drives — names are misleading, so read this).** Each color is \`{ background, color, hover, active }\` (\`hover\`/\`active\` = \`"Auto"\` derives them):
- \`mainColor\` = the **content surface**: the popover/modal/tooltip **background** (\`.background\`) and **body text** (\`.color\`). This is what makes a theme light vs dark. (Also drives borders / the close button.)
- \`brandColor\` = the **accent**: buttons, progress bar, links, survey, focus highlight, resource-center accent. \`.background\` is the accent fill, \`.color\` the text on it.
- \`buttons.primary\` / \`buttons.secondary\` = explicit button colors; omit them and buttons inherit from \`brandColor\` (primary) / \`mainColor\` (secondary).
- Per-widget colors (\`banner\`, \`checklist\`, \`launcher*\`, …) override only that widget.
- **A button can vanish into a colored banner — nothing checks contrast.** A banner has its own \`banner.backgroundColor\`, but a CTA button on it still uses the button colors above: a primary (or \`Auto\`) button is the \`brandColor\` accent. So if you set the banner background to your brand/accent color, a primary CTA is that same color → invisible on it. For a button sitting on a colored banner, give \`buttons.primary\` explicit colors (or use a \`secondary\` button) that contrast with \`banner.backgroundColor\`. Validation never flags same-on-same color.
- **Most themes only need \`brandColor\` + \`mainColor\`.** A common mistake: treating \`mainColor\` as an accent — it's the surface, so a dark \`mainColor.background\` makes the whole popover dark.

**Color format.** Colors are sRGB hex (\`#rrggbb\`). If the app's brand tokens are \`oklch()\` / \`hsl()\` (common in modern shadcn / Tailwind v4), convert them to hex first — and note \`getComputedStyle().color\` returns the raw \`oklch()\` (not hex) on modern browsers, so round-trip through a canvas: \`const x=document.createElement('canvas').getContext('2d'); x.fillStyle='oklch(0.208 0.042 265.755)'; const hex=x.fillStyle;\` (canvas normalizes to \`#rrggbb\`).

**Fonts.** \`font.fontFamily\` is one of: \`"System font"\` (the system stack), \`"Custom font"\` (a self-hosted font — you also set \`font.customFontFamily\` to its \`@font-face\` family name and define the face in \`customCss\`), or **any Google Font name** (e.g. \`"Inter"\`) which the SDK loads automatically. So \`fontFamily: "Inter"\` just works (loaded from Google Fonts); only use \`customFontFamily\` together with \`fontFamily: "Custom font"\`.

## Flow steps
- **\`steps\` is the complete list, not a patch** — any existing step you omit is deleted. To change one step, send them all. Identify a step to update by its \`cvid\` (stable: it survives forking) or primary \`id\`; omit both to create a new step.
- Step \`type\`: \`tooltip\` | \`modal\` | \`hidden\` | \`bubble\`. **Only \`tooltip\` needs a \`target\`** (a CSS selector of an element on the page); the rest are page-level.
- **Placement is shaped by the step kind**: a \`tooltip\` takes \`{ side, align }\` (anchored to its target); a \`modal\` takes \`{ position }\` on the 9-cell viewport grid (e.g. \`"center"\`). Sending the wrong shape for the kind is rejected up front (it would otherwise be silently dropped). A \`bubble\` is positioned by its **theme** (\`bubble.placement\`), so a step-level \`placement\` on a bubble is ignored; \`hidden\` has no UI, so placement doesn't apply.
- Every non-\`hidden\` step needs content; a \`button\` block needs both text and an action; a \`question\` block needs a name.
- **Wire navigation by step \`key\`**: give a step \`"key": "pricing"\`, and a button action elsewhere in the SAME write does \`{ "type": "goto_step", "step": "pricing" }\`. Keys are write-only handles; forward and cyclic links work in one call. (You may also target an existing step by its \`cvid\`.)
- **Advance when the user clicks the targeted element**: set the step's \`onClick\` to an action array, e.g. \`[{ "type": "goto_step", "step": "pricing" }]\`. \`onClick\` fires on the real page element the tooltip points at — distinct from a \`button\` block's action (a button rendered inside the tooltip). Tooltip steps with a \`target\` only.
- **React to page state, not only buttons — \`triggers\`**: a step can carry \`"triggers": [{ "when": [<conditions>], "do": [<actions>], "waitMs"?: <ms> }]\`. The \`do\` actions fire when the \`when\` conditions become true, however the user got there — \`when\` is polled live in the browser, so it takes only the client-evaluable condition types (\`attribute\` / \`current_url\` / \`element\` / \`text_input\` / \`text_filled\` / \`time_window\` / \`group\`; \`event\` / \`segment\` / \`content_state\` are server-evaluated and rejected here — put those in start/hide rules); \`do\` takes the same actions as a button. Use it so a step isn't stranded when the user acts on the page instead of clicking your button: e.g. a tooltip on a nav link with \`"when": [{ "type": "current_url", "includes": ["*/tasks"] }]\` → \`"do": [{ "type": "goto_step", "step": "next" }]\`. Layer \`onClick\` + a \`trigger\` + a button so every path advances.
- **Cross-page tooltip targets.** A tooltip step whose target isn't on the page where the step is reached is, by default, silently dropped and the whole flow ends (theme \`tooltip.missingTargetBehavior: "auto-dismiss"\`, after \`tooltip.missingTargetTolerance\` seconds) — no error. For a flow that crosses pages: (1) set the theme \`tooltip.missingTargetBehavior: "use-bubble"\` so a missing target degrades to a floating bubble instead of vanishing (and/or raise \`tooltip.missingTargetTolerance\` for targets that render just after navigation); and (2) advance with a \`current_url\` trigger (optional \`waitMs\`) so you reach the tooltip step only once you're on the page its target lives on. The pitfall: navigating to page A while the next tooltip's target is on page B — the target is absent on arrival and the step disappears silently.

## Text (markdown subset)
Paragraphs; \`# \`/\`## \` headings (h1/h2 only — NO h3+); \`-\`/\`*\` and \`1.\` lists; \`\`\` code fences. Inline: \`**bold**\`, \`*italic*\`, \`[text](url)\`, and \`{{ attribute_code | default: "x" }}\` for user attributes (list codes with \`list_attribute_definitions\`).
**Anything outside this subset is silently normalized, not rejected** — so it won't error, but it also won't render as you wrote it: h3+ collapses to h2; blockquotes become plain paragraphs; tables, horizontal rules (\`---\`), strikethrough, inline images, inline \`code\`, and liquid filters other than \`default\` are dropped. Read a value back (or \`validate_content_version\`) if you're unsure it survived.

## Targets
A \`target\` identifies one element by a CSS \`selector\`, optionally refined by \`nth\` and/or \`text\` (both optional). The runtime targets the FIRST \`selector\` match unless \`nth\` (0-based) picks another — so either use a selector unique to that element, or pair a stable non-unique selector with \`nth\` (e.g. \`{ "selector": ".toolbar button", "nth": 2 }\`). \`text\` requires the targeted element's exact visible text — use it to pin a content/state (e.g. \`{ "selector": "#status-btn", "text": "Published" }\`); it refines the element already chosen by \`selector\`/\`nth\` and does NOT by itself search among matches, so a non-unique selector with only \`text\` (no \`nth\`) targets the first match and silently won't render. \`nth\` supports 0–4 today. If the element has no stable selector, add one (\`id\`/\`data-*\`) in your app source on that single element; if you can't confirm the target from source/DOM, ask for a verified selector.

## Start rules & frequency
\`startRules.frequency.mode\`: \`once\` (single show) | \`multiple\` (up to N per window) | \`unlimited\` (every match). \`multiple\`/\`unlimited\` use an \`every\` window (\`{ times?, duration, unit }\`); \`once\` ignores it.

**Start-rule knobs are type-gated — setting an unsupported one is rejected (e.g. \`frequency\` on a banner → E1017).** \`frequency\`, \`waitMs\`, \`startIfNotComplete\` are **flow + checklist** only (\`frequency.atLeast\`, flow only); \`priority\` is flow + checklist + resource-center. **Banner and launcher accept none of these — they have no \`frequency\` knob.** But "no frequency" does NOT mean "reshows on every match": **Banner, Launcher, and Resource Center are single-session** — at most ONE session per (user, content) over the user's whole lifetime. The user sees it once; once they dismiss it (or it ends), it **never auto-starts again** for them, even while its \`startRules\` still match — there is no \`frequency\` to make it recur (that knob is flow/checklist only). So a banner is a **one-time-per-user announcement, not a persistent always-there strip**; for a recurring message a banner is the wrong tool. \`diagnose_content\` shows this as a \`single_session\` gate. (Flows and checklists instead repeat per their \`frequency\`.)

**Condition shapes.** Each \`when\` entry is an object keyed on \`type\` — exact values: \`attribute\`, \`segment\`, \`current_url\`, \`element\`, \`content_state\`, \`event\`, \`text_input\`, \`text_filled\`, \`time_window\`, \`group\` (an AND/OR of nested conditions). The user/company attribute condition is \`type: "attribute"\` with a **required \`scope\`** (\`user\` | \`company\` | \`companyMembership\`) — there is **no** \`user_attribute\` / \`user-attr\`. (Exact fields per type: \`get_content_schema\`.) **Multiple top-level \`when\` entries are AND'd** — \`when: [A, B]\` means A AND B, NOT A OR B; to OR two conditions wrap them in one \`{ "type": "group", "match": "any", "conditions": [A, B] }\` (\`match: "all"\` = AND, \`"any"\` = OR). Validation checks attribute/operator/scope but does NOT check satisfiability — a self-contradictory group (e.g. \`scope:user plan is "pro"\` AND \`plan is "free"\`) validates clean and then simply never matches at runtime, so double-check that a group CAN be true.

**To detect "the user finished an action", prefer an app-fired \`event\` over \`element\` state on a transient target.** An \`element\` condition with \`state: "hidden"\` (or \`present\`) on a thing that animates or mounts/unmounts — a modal/drawer/dropdown, a portaled overlay, a toast — transiently matches DURING the open/close transition (the node is briefly absent or off-screen mid-animation), so a trigger / checklist \`completeWhen\` keyed on it can fire a false "done" (e.g. celebrating before the user did anything). For "did X happen", have the host \`usertour.track("x_done")\` and gate on \`{ "type": "event", "event": "x_done" }\` — an event is a discrete fact, not a fragile read of DOM presence. Reserve \`element\` conditions for steady-state checks (a button is genuinely present/disabled), not for catching the moment an action completes.

**Targeting "new users" is an audience, not just a frequency.** \`frequency: once\` means "show each matching user a single time" — NOT "only recently-created users"; every user still hits it once. For a true recency audience add an \`attribute\` condition (scope \`user\`) on a date attribute (e.g. \`first_seen_at\`, op \`less_than\`, value \`7\` = first seen in the last 7 days), or make a \`segment\` for it and gate on that — then pair it with \`frequency: once\` so new users see it exactly once.

**\`current_url\` patterns (NOT substring, NOT regex).** \`includes\`/\`excludes\` are arrays of **URL patterns** matched against the WHOLE url (anchored). Syntax: \`*\` is a wildcard within one url part (doesn't cross \`/\`); \`:name\` matches one path segment. **Omitting a part means "any" for it — most importantly, a pattern with NO path matches EVERY path (the whole site).** So scope by writing the path:
- only the homepage → \`*/\` (path is exactly \`/\`)
- one exact page → \`*/pricing\`
- a section and everything under it → \`*/app/*\`
- **any page at all → \`*\` (NOT \`*/\`).** \`*/\` matches only a bare ROOT path (\`https://x.com/\`) — not \`/app\`, not \`/app/\`, not any deeper page — so a rule built on it fires almost nowhere.
- any page on a host → \`yourapp.com/*\` (or omit the path)
- exclude an area → put \`*/app/admin/*\` in \`excludes\`

(Scheme is usually omitted = any; the domain may use \`*\` for subdomains. A flow matches when it hits an \`includes\` pattern and no \`excludes\` pattern.)

**Auto-start is the presence of \`startRules\` — there is no separate on/off flag.** Include \`startRules\` with ≥1 \`when\` condition to make a flow launch by page conditions; omit \`startRules\` to leave it start-on-demand only. (Don't look for an \`enabled\` field — the server derives it from whether you sent any rules.)

**Launcher / Banner / Resource Center appear ONLY when their \`startRules\` match — there is no ambient "always on" mode.** Unlike a flow you can fire with \`usertour.start()\`, these persistent surfaces have no first-show path other than auto-start matching (a Banner is re-evaluated on every page; a Launcher / Resource Center needs a match to create its first session). With no \`startRules\` the launcher / banner never renders and \`openResourceCenter()\` stays a no-op — publish still succeeds, but \`validate_content_version\` flags it as a warning. For an always-available help hub or launcher, give a permissive \`current_url\` rule that matches the whole site (per the URL-pattern note above, omit the path part); scope it down when it should only show on some pages.

**Sequence auto-starting content so several pieces don't pile onto the first screen.** A \`when\` condition \`{ "type": "content_state", "content": "<contentId>", "state": "seen" | "unseen" | "completed" | "uncompleted" | "active" | "inactive" }\` gates one content on another's state. (The referenced piece must be a **flow or a checklist** — only those record per-user state. Referencing a **banner / launcher / resource center** is REJECTED at write — those carry no such state, so use a different gate, e.g. a \`current_url\` rule.) To reveal a second surface only after the first has run and closed, gate its \`startRules.when\` on the first — e.g. require the welcome flow be \`seen\` AND \`inactive\`: \`{ "type": "group", "match": "all", "conditions": [{ "type": "content_state", "content": "<welcomeId>", "state": "seen" }, { "type": "content_state", "content": "<welcomeId>", "state": "inactive" }] }\`. (Combine conditions with a \`group\`: \`match: "all"\` = AND, \`"any"\` = OR.)

**One of each singleton type shows at a time — \`priority\` orders only FRESH candidates.** Flow / checklist / banner / resource-center are singletons: at most one of each type is active at once. When the user already has an in-progress (resumable) session of that type, the runtime RESUMES it BEFORE auto-starting anything new — so a brand-new piece won't appear until that session ends, and raising its \`priority\` won't make it jump the active one (\`priority\` only breaks ties among fresh auto-start candidates, never against a resume). This is why a freshly published flow can pass every gate yet not show on a screen that already has one running. \`diagnose_content\` surfaces it: an \`active_slot\` gate (another piece holds the slot) vs an \`outranked\` gate (a higher-priority fresh sibling wins).

**No auto-start ≠ unreachable.** With no \`startRules\` (or when none match) the content won't launch on its own — but it can still be started programmatically from the host app via the SDK \`usertour.start(contentId)\` call. Choose this when you want to trigger content from your own button/route rather than by page conditions.

**Wiring pieces to LAUNCH each other — reference a PUBLISHED \`contentId\`.** To make one piece start another, put a \`start_content\` action on a button / checklist-item \`clickActions\`: \`{ "type": "start_content", "content": "<contentId>" }\` (a flow or checklist contentId from \`list_content\` — a raw content id, NOT a step key like \`goto_step\` takes). To re-surface flows/checklists from a Resource Center, list them in a \`content-list\` block: \`items: [{ "content": "<contentId>", "contentType": "flow" | "checklist" }]\`. **Publish the referenced pieces BEFORE the piece that references them:** \`validate_content_version\` rejects a contentId that doesn't EXIST, but it does NOT check that the target is PUBLISHED — a reference to an unpublished draft validates + publishes clean yet launches / lists nothing for a real user. So in a multi-piece program, create + publish the dependencies (the launched flows) first, then wire the checklist / resource center to their ids.

**The standard onboarding shape: a checklist of tasks, each task launching a guide FLOW.** When the job is "walk new users through N setup tasks", do NOT hand-roll it with \`navigate\` clicks plus \`element\`-clicked completion — that pattern leaves any guide flows you built ORPHANED (nothing starts them) and makes task completion hostage to selectors that may not exist. The proven wiring, per task:
1. Build one guide flow per task (multi-step: tooltip anchored on the real control, advance on interaction, \`dismiss\` on the last step). Leave the flow's auto-start DISABLED — the checklist is its start path.
2. Publish the flows FIRST, then wire each checklist item:
   - \`clickActions: [{ "type": "start_content", "content": "<flowId>" }]\` — clicking the task starts its guide (prepend a \`navigate\` action when the guide's page is elsewhere);
   - \`completeWhen: [{ "type": "content_state", "content": "<flowId>", "state": "completed" }]\` — the task checks itself off when the user finishes the guide. No selector involved, nothing to break.
3. Publish the checklist to the SAME environment as the flows.
Before you call the build done, walk every flow you created and confirm it has a start path — auto-start rules, an inbound \`start_content\`, or a resource-center \`content-list\` entry. A flow with auto-start disabled that nothing references is published yet UNREACHABLE: no user can ever see it. **Default to a guide flow for EVERY task that involves doing something in the UI** — an item that only navigates and then waits for a click gives a new user no direction at all ("the page opened… now what?"), exactly the low-value shape this recipe exists to prevent. Skip the guide flow only when the task is self-evident (e.g. "finish the welcome tour" itself) or its completion signal is an app-fired \`event\` for an action the user already knows how to do.

## Making it appear (the SDK)
Authoring + publishing only stores the content — it renders only once the host app loads the Usertour SDK. You author here; the app does these (see https://docs.usertour.io/developers/usertourjs-reference/installation):
- **Identify with the SAME id you target.** The app calls \`usertour.identify(userId, attrs)\`; that \`userId\` must equal the \`externalId\` your segments / start-rules / attribute conditions match on. Mismatch = content validates and publishes but never shows for that user (the most common "why isn't it appearing").
- **SDK token ≠ API token.** \`usertour.init(token)\` takes the **environment token** (a public, client-side key). NEVER put the API token (the secret \`utp_…\` used for this MCP) in client code — it grants full project write access.
- **Publish env must match the app's token.** Each environment has its own SDK token (\`list_environments\`). Content published to environment X shows only in an app whose \`init()\` used X's token — publishing to one environment while the app runs another's token is another "why isn't it showing".

**Diagnosing + verifying it shows.** For the server-side "should this show for this user" question (published? identified? conditions / frequency / slot?), call \`diagnose_content\` — it returns a per-gate checklist plus the exact failing condition (with the user's actual attribute value), so you don't have to guess. **\`diagnose_content\` checks whether the whole CONTENT shows — the content-level gates (published / identified / start_rules / frequency / single_session / hidden) — NOT whether individual items or blocks inside it show or complete.** A checklist item's \`completeWhen\`, a resource-center item/block's \`onlyShowWhen\`: those are per-item runtime render decisions diagnose does not evaluate, so it returns the SAME result for an admin and a non-admin even when an item is gated to admins only. Confirm item-level visibility / completion in the running app, not via diagnose. Diagnosing OFFLINE (no app running yet)? \`diagnose_content\` evaluates the per-user gates against a user that must already exist in the environment — seed your test externalId with \`upsert_user\` first, AND set the attributes your start rules / segments test against. (Just creating the user isn't enough: an existing user with no attributes passes the \`identified\` gate but fails \`start_rules\` with the segment/attribute \`unmatched\`, sending you to hunt in the wrong place.) **One thing you CAN'T seed offline: "has seen / completed another content".** \`upsert_user\` sets attributes, not session history — and a \`content_state\` gate (\`seen\` / \`completed\` / \`active\` …) is evaluated against the user's REAL session history. A freshly seeded test user has none, so such a gate always reads as not-yet-satisfied. That means diagnose can confirm a sequencing gate is currently BLOCKING ("tour blocked: welcome flow not yet seen" — which is correct, not a misconfig) but can't simulate the satisfied case; verify the positive path (the tour DOES fire once the gating flow has actually been seen) in the running app, not offline. To verify it actually RENDERS in the running app: the SDK draws content inside its OWN iframes (e.g. \`iframe.usertour-widget-surface-viewport\` for a flow, \`usertour-widget-banner-frame\` for a banner) — NOT the host page's document. So checking \`document.body.innerText\` / waiting for your text in the main DOM never matches even when it's on screen; instead take a screenshot, or read \`iframe.contentDocument.body.innerText\` (same-origin). To force a specific flow on screen for a check (bypassing auto-start gating + the single-slot resume), call \`usertour.start(contentId)\` in the page. One boundary: \`usertour.start()\` cannot replay a SINGLE-SESSION surface (banner / launcher / resource center) for a user who has already had their one session — it bypasses start rules, not the lifetime session record, so nothing appears and nothing errors. To preview changes to one of these, identify a FRESH test user who has never seen it.

## Host integration dependencies (you author these; the host wires the hook)
Some authoring choices only work if the host app wired a matching SDK hook. They publish fine and then fail **silently** at runtime — so flag the dependency when you use the feature and point the developer at the usertour.js reference (https://docs.usertour.io/developers/usertourjs-reference/installation) plus the package's TypeScript types (\`usertour.d.ts\`) for exact signatures. The identify ↔ externalId link above is one of these; the rest:
- **A same-window \`navigate\` action mid-flow** does a **full page reload** unless the host called \`usertour.setCustomNavigate()\` (SPA soft-nav). A reload drops the in-progress flow (the Resource Center survives a reload; flows do not). For a flow that must continue on another page: either rely on \`setCustomNavigate\` (you control an SPA), **or don't carry one flow across the navigation** — make the destination-page guidance its own content triggered by a \`current_url\` start rule (portable and reload-proof).
- **\`text_input\` / \`text_filled\` conditions (and "continue when filled" triggers) on a custom input** (combobox, custom dropdown, contenteditable): the SDK reads values only from native \`<input>\` by default, so the condition never matches unless the host called \`usertour.registerCustomInput()\`.
- **A \`tooltip\` target inside a custom scroll container or sticky-header layout**: default smooth-scroll can land the element under a fixed header or fail to scroll a custom container; the host fixes positioning with \`usertour.setCustomScrollIntoView()\`.
- **SDK UI hidden behind the app's modals/overlays**: the host raises it with \`usertour.setBaseZIndex()\` (default ≈ 1,000,000).
- **\`current_url\` conditions when the URL carries sensitive/dynamic data** (tokens or ids in the path/query): the SDK sends and matches the **full** URL; the host can sanitize with \`usertour.setUrlFilter()\` — then write your patterns against the sanitized form.
- **External links in content that need auth/tracking params**: the host adds them per click with \`usertour.setLinkUrlDecorator()\`.

## Surveys & questions
A survey is a **flow** with \`question\` blocks in its steps — there is **no separate survey type**, and \`question\` blocks work **only in flow steps** (one in a checklist / banner / resource-center is rejected at write). Put a \`question\` block in a step's \`content\` — **at most ONE question per step** (the builder allows only one, and the runtime reads only the FIRST question in a step, so a second is invisible). A multi-question survey = one question PER step, chained. **A question's \`name\` is an analytics label, NOT the visible prompt** — the widget renders only the input (scale / options / text field), never the \`name\`. For the question text the user actually reads, add a \`text\` block in the SAME step before the question block; a question with only a \`name\` shows bare options with no prompt. (At runtime nps / rating / single-select fire the question's actions on **pick**; multi-select and text fire them via their **Submit** button.) **A question does NOT advance to the next step on its own** — put a \`goto_step\` in the question block's OWN \`actions\` (fired by that pick / submit), or advance the step via a \`trigger\`. Do NOT add a separate \`button\` block just to advance: a question already has its own submit affordance, so a second button doubles up (a \`text\` question always renders its own \`buttonText\` button). A question with no \`goto_step\` action and no trigger records the answer then stalls — \`validate_content_version\` flags the next step "not reachable" (correctly). **Prefer the question's own \`goto_step\` action (it fires on the actual answer) over a \`trigger\` that merely checks the bound attribute has a value**: a \`when\` like "attribute _is any_" is already true the instant the step opens for any returning user who previously answered (the attribute is set), so the step is skipped before they see the question — scope any advance to the in-session answer, not "the attribute exists". **Editing a survey later:** to keep a question's response analytics continuous across edits, echo its \`cvid\` (read it from \`get_content_version expand:["steps"]\`) in the \`question\` block you write back — the cvid is the question's analytics identity, and a write that omits it gives the question a new one (breaking the tie to prior responses). Four kinds (keyed on \`kind\`):
- **nps** — a 0–10 "how likely to recommend" score; the 0–10 range is **fixed** (no \`range\` field). \`lowLabel\`/\`highLabel\` optional.
- **rating** — needs \`style\` (\`star\` | \`scale\`) + a \`range\` (e.g. \`{ low: 1, high: 5 }\`). A "scale" question is just \`style: "scale"\` — there is **no** separate \`scale\` kind.
- **text** — needs \`multiline\` (true/false); \`placeholder\` / \`buttonText\` / \`required\` optional. **\`text\` is the ONLY kind with \`required\`** — nps / rating / choice can't be made mandatory. **A text question renders its OWN submit button** (its \`buttonText\`), so a step ending in a text question already shows a button — don't add a separate \`button\` block beside it or the step shows two buttons.
- **choice** — needs \`options: [{ label, value }]\` (the \`value\` is what's stored) + \`allowMultiple\`; \`enableOther\` / \`otherPlaceholder\` / \`shuffle\` optional. A multi-select (\`allowMultiple: true\`) answer needs a \`list\`-typed bound attribute.

**Capturing answers.** Every answer is recorded as a response event regardless of binding. Set a question's \`bindAttribute\` to **also** store the answer on a user attribute (for targeting/segmentation): pass the attribute **codeName** (create it first with \`create_attribute_definition\`), NOT its id. It is **not validated** — a wrong/typo'd code publishes and then silently captures nothing. Match the attribute dataType to the answer (number for nps/rating, string for single-select, list for multi-select). Leave \`bindAttribute\` unset for free prose you won't target on (it's still captured as the response event).

**Reading results.** \`get_content_question_analytics\` aggregates nps / rating / choice questions (score, distribution, averages) but **omits text questions entirely** — free text has no aggregate signal. To read what people actually wrote (or to double-check any answer), call \`list_sessions\` with \`expand:["answers"]\`: each session's \`answers[]\` carries every question's raw \`answerValue\`, text included.

## What each type needs to be usable (else publish is rejected)
- **flow**: ≥1 step; tooltip steps have a target; non-hidden steps have content; goto targets resolve.
- **checklist**: ≥1 item; each item has a name AND a click action or a completion condition.
- **launcher**: a target; show-tooltip behavior needs tooltip content; perform-action behavior needs actions.
- **banner**: content; element-relative placements need a container element.
- **resource-center**: ≥1 tab; each tab has a name and ≥1 block. Tab blocks use their OWN vocabulary (\`richtext\`, \`divider\`, \`action\`, \`sub-page\`, \`content-list\`, \`live-chat\`) — text goes inside a \`richtext\` block: \`{ "type": "richtext", "content": [{ "object": "block", "type": "text", "markdown": "…" }] }\`, NOT a bare text block.
- **tracker**: a \`data.event\` AND \`startRules\` trigger conditions; no theme (it has no UI). A tracker is **headless** — it fires its event whenever its \`startRules\` conditions are met. The event MUST be a **custom** event (its codeName or id from \`list_event_definitions\`; accepted either way, stored as the codeName) — built-in / **system (predefined) events are rejected**: a tracker can only fire custom events, so create one first with \`create_event_definition\` if you don't have a suitable one. Note: a \`current_url\` condition's \`includes\`/\`excludes\` are **arrays** of strings (and \`["*"]\` = the whole site, every page).

## Builtin icon names (resource center + launcher)
An icon field with \`source: "builtin"\` takes a **RemixIcon** name in \`-line\` / \`-fill\` kebab style — **NOT lucide names**. A name that isn't in the set renders **nothing, silently** (no error). So don't guess lucide-style names like \`help-circle\`, \`book-open\`, \`sparkles\`, \`message-circle\` — they will not render. Intent → valid name:
- help / support → \`question-line\` · chat / message → \`chat-line\` · home → \`home-line\` · settings → \`settings-line\`
- new / launch → \`rocket\` · doc / file → \`file-text-line\` · list / menu → \`list-check\` or \`menu-line\` · search → \`search-line\`
- star / favorite → \`star-line\` · notification → \`notification-line\` · check → \`check-line\` · info → \`information-fill\` · mail → \`mail-line\`
Names are \`thing-line\` / \`thing-fill\` (e.g. \`home-line\`, \`home-fill\`). **No builtin exists for some concepts (book, keyboard, sparkles) — use a near match or, when unsure, \`source: "none"\` rather than a guess that silently fails.**
`;
