import { Content, ContentDataType, Environment, Step } from '@usertour/types';

/**
 * Convert content list type (plural) to ContentDataType enum
 * e.g., 'flows' -> ContentDataType.FLOW, 'launchers' -> ContentDataType.LAUNCHER
 */
export const getQueryType = (contentType: string): ContentDataType => {
  const typeMap: Record<string, ContentDataType> = {
    flows: ContentDataType.FLOW,
    launchers: ContentDataType.LAUNCHER,
    banners: ContentDataType.BANNER,
    checklists: ContentDataType.CHECKLIST,
    trackers: ContentDataType.TRACKER,
    'resource-centers': ContentDataType.RESOURCE_CENTER,
    announcements: ContentDataType.ANNOUNCEMENT,
  };
  return typeMap[contentType] ?? ContentDataType.FLOW;
};

export const isPublishedInAllEnvironments = (
  content: Content | null,
  environmentList: Environment[] | null,
  versionId: string | null | undefined,
) => {
  // Early return if any required data is missing
  if (!content?.contentOnEnvironments?.length || !environmentList?.length || !versionId) {
    return false;
  }

  // Check if all environments have the version published
  return environmentList.every((env) =>
    content?.contentOnEnvironments?.some(
      (item) =>
        item.published && item.publishedVersionId === versionId && item.environment.id === env.id,
    ),
  );
};

export const isPublishedAtLeastOneEnvironment = (content: Content | null) => {
  if (content?.contentOnEnvironments && content?.contentOnEnvironments?.length > 0) {
    return true;
  }
  return false;
};

export const isVersionPublished = (content: Content, versionId: string): boolean => {
  return Boolean(
    content?.contentOnEnvironments?.find(
      (env) => env.published && env.publishedVersionId === versionId,
    ),
  );
};

/**
 * Resolve the editable version id before writing: ALWAYS asks the server via
 * the passed `createVersion` mutation and returns the id to write to. The
 * server owns the freeze rule (live now, EVER live — unpublish does not
 * unlock — or superseded; see content.service.ts versionFrozen) and the
 * mutation is idempotent under a row lock: an already-editable draft is
 * returned as-is (no fork, same id), a frozen version forks.
 *
 * Deliberately NO client-side pre-check: an earlier local predicate here only
 * knew "currently live", so a published-then-unpublished version skipped the
 * fork and every save crashed into the server's E0049 wall. Keeping a client
 * copy of the freeze rule re-creates that drift the next time the rule moves;
 * asking the rule's owner cannot.
 *
 * Throws when the resolve fails — callers own error presentation. `config` is
 * applied server-side to the resolved draft (fork or reuse); omit it to leave
 * the draft's config untouched (a fork then keeps the source's config).
 * Compare the returned id with the one you passed to detect a fork.
 */
export const resolveEditableVersionId = async (
  versionId: string,
  createVersion: (data: {
    versionId: string;
    config?: unknown;
  }) => Promise<{ id?: string } | null | undefined>,
  config?: unknown,
): Promise<string> => {
  const created = await createVersion({ versionId, config });
  if (!created?.id) {
    throw new Error('Failed to create a new version');
  }
  return created.id;
};

/**
 * Stable identity for a flow step — the `step/:stepId` route param shared by the
 * flow builder (navigation, sortable list, preview key) and content detail's
 * deep-link into a step, so both agree on what "this step" is. Prefer the cvid:
 * it's the front-end-generated id that is PRESERVED when a version is forked,
 * whereas the server id is a per-version database row id that is regenerated by
 * the fork. Opening the builder on a published content forks a fresh editable
 * version (resolveEditableVersionId → createContentVersion) and gives every step
 * a new server id; keying on the server id made detail's deep-link point at an
 * id that no longer exists in the forked version → blank editor. The index
 * suffix only guards a step that carries neither and never navigates.
 */
export const getStepId = (step: Step, index: number): string => {
  return step.cvid ?? step.id ?? `step-${index}`;
};
